<section class="user-image-section"> 
	<img src="../images/user.svg">
	<div>Přihlášen: <span><?= $userName ?></span></div>
</section>
<section class="user-data-section">	
	<div class="user-data-item">
		<span class='user-property-name'>ID</span>
		<span class='user-property-value'><?= $userId ?></span>
	</div>	
	<div class="user-data-item">
		<span class='user-property-name'>Jméno</span>
		<span class='user-property-value' id="username"><?= $userName ?></span>
		<div class='user-property-action'>
			<button class="btn border-btn non-transparent black" id="change-name-button">Vyžádat změnu</button>
		</div>
		<div id="change-name" style="display: none;">
			<label for="change-name-new">Nové jméno</label>
			<input class="text-field" id="change-name-new" type=text maxlength=15 />
			<button class="btn border-btn non-transparent black" id="change-name-confirm-button">Potvrdit</button>
			<button class="btn inline black" id="change-name-abort-button">Zrušit</button>
		</div>
	</div>
	<div class="user-data-item">
		<span class='user-property-name'>Heslo</span>
		<span class='user-property-value'>[Skryto]</span>
		<div class='user-property-action'>
			<button class="btn border-btn non-transparent black" id="change-password-button">Změnit</button>
		</div>
		<div id="change-password" style="display: none;">
			<label for="change-password-old">Staré heslo</label>
			<input class="text-field" id="change-password-old" type=password maxlength=31 />
			<label for="change-password-new">Nové heslo</label>
			<input class="text-field" id="change-password-new" type=password maxlength=31 />
			<label for="change-password-re-new">Nové heslo znovu</label>
			<input class="text-field" id="change-password-re-new" type=password maxlength=31 />
			<button class="btn border-btn non-transparent black" id="change-password-confirm-button">Potvrdit</button>
			<button class="btn inline black" id="change-password-abort-button">Zrušit</button>
		</div>
	</div>
	<div class="user-data-item">
		<span class='user-property-name'>E-mail</span>
		<span class='user-property-value' id="email-address"><?= $userEmail ?></span>
		<div class='user-property-action'>
			<button class="btn border-btn non-transparent black" id="change-email-button">Změnit</button>
		</div>
		<div id="change-email" style="display: none;">
			<label for="change-email-password">Heslo</label>
			<input class="text-field" id="change-email-password" type=password maxlength=31 />
			<label for="change-email-new">Nový email</label>
			<input class="text-field" id="change-email-new" type=text maxlength=255 />
			<button class="btn border-btn non-transparent black" id="change-email-confirm-button">Potvrdit</button>
			<button class="btn inline black" id="change-email-abort-button">Zrušit</button>
		</div>
	</div>
	<div class="user-data-item">
		<span class='user-property-name' title="Pro zvýšení přidávejte obrázky">Přidané obrázky</span>
		<span class='user-property-value'><?= $addedPictures ?></span>
	</div>
	<div class="user-data-item">
		<span class='user-property-name' title="Pro zvýšení se nechejte testovat">Uhodnuté obrázky</span>
		<span class='user-property-value'><?= $guessedPictures ?></span>
	</div>
	<div class="user-data-item">
		<span class='user-property-name' title="Karmu získáte za činnost vedoucí ke zlepšení služby">Karma</span>
		<span class='user-property-value'><?= $karma ?></span>
	</div>
	<div class="user-data-item">
		<span class='user-property-name'>Status</span>
		<span class='user-property-value'><?= $status ?></span>
	</div>
</section>

<button class="btn border-btn non-transparent black" id="delete-account-button" onclick="deleteAccount()">Odstranit účet</button>
<div id="delete-account-input1" style="display:none;">
	<input class="text-field" id="delete-account-input-field" type=password maxlength=31 />
	<button class="btn border-btn non-transparent black" id="delete-account-confirm-button" onclick="deleteAccountVerify()">OK</button>
</div>
<div id="delete-account-input2" style="display:none;">
	<span>Tato akce je nevratná. Opravdu si přejete trvale odstranit svůj účet?</span><br>
	<button class="btn border-btn non-transparent black" id="delete-account-final-confirm-button" onclick="deleteAccountFinal()">Ano, odstranit účet</button>
	<button class="btn border-btn non-transparent black" id="delete-account-final-cancel-button" onclick="deleteAccountCancel()">Ne, zrušit odstranění účtu</button>
</div>