<div id="add-pictures-form-wrapper">
    <label for="add-natural-select">Zvol přírodninu, jejíž obrázek chceš přidat:</label>
    <div class="custom-select-wrapper" id="add-natural-select">
        <div class="custom-select">
            <div class="custom-select-main">
                <span></span>
                <img class="arrow" src="images/arrow-black.svg" alt="Ikona šipky">
            </div>
            <ul class="custom-options">
                <?php foreach ($naturals as $natural) :?>
                    <li class="custom-option">
                        <?= $natural->getName() ?> (<?= $natural->getPicturesCount() ?>)
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <input type="hidden" name="naturalName" id="natural-name-hidden" value="" />
    <div class="form add-pictures-url disabled">
        <label for="url-input">Zadej URL adresu obrázku:</label>
        <input type=url name="url" id="url-input" class="text-field" value=""/>
        <button id="url-confirm-button" class="btn border-btn black non-transparent submit-button">OK</button>
    </div>
    <div class="add-pictures-preview disabled">
        <a id="commons-link" class="btn border-btn black non-transparent" target="_blank" rel="noopener">
            <span><b>Vyhledat na Commons</b></span><img class="logo" src="images/commons-logo.png" alt="Logo Wikimedia Commmons">
        </a>
        <a id="duck-link" class="btn border-btn black non-transparent" target=_blank rel="noopener">
            <span>Vyhledat na DuckDuckGo</span><img class="logo" src="images/duck-logo.png" alt="Logo DuckDuckGo">       
        </a>  
        <a id="google-link" class="btn border-btn black non-transparent" target=_blank rel="noopener">
            <span>Vyhledat na Google</span><img class="logo" src="images/google-logo.png" alt="Logo Google">       
        </a>  
        <button id="submit-picture-button" class="btn border-btn black non-transparent">Přidat obrázek</button>
    </div>
    <div class="add-pictures-picture">
        <img id="preview-img" class="img" src="images/blank.gif" alt="Nenačtený obrázek">
        <img id="preview-img-hidden" style="display: none;" alt="Nenačtený obrázek">
    </div>
</div>
