<div class="overlay"></div>
<div class="container">
    <nav>
        <a id="tab1link" onclick="firstTab()">Správa účtů</a>
        <a id="tab2link" onclick="secondTab()">Správa hlášení</a>
        <a id="tab3link" onclick="thirdTab()">Správa změn jmen</a>
        <a id="tab4link" onclick="fourthTab()">Poslat e-mail</a>
        <a id="tab5link" onclick="fifthTab()">Ovládání databáze</a>
        <a href="menu">Návrat</a>
    </nav>
    <main>
        <div id="tab1">
            <?php require 'Views/usersTable.phtml'; ?>
        </div>
        
        <div id="tab2">
            <?php require 'Views/reportsTable.phtml'; ?>
        </div>
        <div id="tab3">
            <?php require 'Views/NameChangesTable.phtml'; ?>
        </div>
        <!--
        <div id="tab4">
            <div id="email">
                <table>
                    <tr>
                        <td><span>Adresát:</span></td>
                        <td><input id="emailAddressee" type=email maxlength=255 /></td>
                    </tr>
                    <tr>
                        <td><span>Předmět:</span></td>
                        <td><input id="emailSubject" type=text maxlength=70 /></td>
                    </tr>
                </table>
                <textarea id="emailMessage" rows="20" cols="70" placeholder="Zpráva"></textarea>
                <div id="emailPreview" style="display:none;">
                    <span>Zde se zobrazí náhled e-mailu:</span>
                </div>
                <table>
                    <tr>
                        <td><span>Bezpečnostní kód: </span></td>
                        <td><input id="emailCode" type=text maxlength=8 value="<php> include 'php/included/CONSTANTS.php'; echo EMAIL_CODE;</php>" /></td>
                    </tr>
                </table>
                <button id="emailPreviewButton" class="borderBtn" onclick="previewEmailMessage()">Zobrazit náhled</button>
                <button id="emailSendButton" class="borderBtn" onclick="sendMail()">Odeslat</button>
            </div>
        </div>
        <div id="tab5">
            <div id="sql">
                <div id="sqlWarning" class="sqlCenter">
                    Neuvědomělé používání tohoto nástroje může mít destruktivní účinky. Používejte tento nástroj pouze v případě, že jste si naprosto jistí tím, co děláte!
                </div>
                <div id="sqlQuery" class="sqlCenter">
                    <textarea id="sqlQueryInput" rows=5 cols=150 placeholder="Zadejte příkazy. Každý příkaz musí být ukončen středníkem (;)"></textarea>
                    <br>
                    <button class="borderBtn" onclick="sendSqlQuery()">Odeslat</button>
                </div>
                <div id="sqlResult">
                    <span class='sqlCenter'>Žádný výstup</span>
                </div>
            </div>
        </div>
    -->
    </main>
</div>