<div class="overlay"></div>
<div class="container">
    <nav>
        <a id="tab1link" onclick="firstTab()">Správa účtů</a>
        <a id="tab2link" onclick="secondTab()">Správa tříd</a>
        <a id="tab3link" onclick="thirdTab()">Správa hlášení</a>
        <a id="tab4link" onclick="fourthTab()">Správa změn jmen</a>
        <a id="tab5link" onclick="fifthTab()">Poslat e-mail</a>
        <a id="tab6link" onclick="sixthTab()">Ovládání databáze</a>
        <a href="menu">Návrat</a>
    </nav>
    <main>
        <div id="tab1">
            <?php require 'Views/usersTable.phtml'; ?>
        </div>
        <div id="tab2">
        	<?php require 'Views/classesTable.phtml'; ?>
        </div>
        <div id="tab3">
            <?php require 'Views/reportsTableAdministrate.phtml'; ?>
            <?php require 'Views/reportedPicturePreview.phtml'; ?>
        </div>
        <div id="tab4">
            <?php require 'Views/nameChangesTable.phtml'; ?>
        </div>
        <div id="tab5">
            <?php require 'Views/emailForm.phtml'; ?>
        </div>
        <div id="tab6">
            <?php require 'Views/sqlForm.phtml'; ?>
        </div>
    </main>
</div>