<button class='btn icon import-alerts-button' title='Načte nové chyby z logu'>Načíst nové chyby</button>
<small>Tlačítko "Načíst nové chyby" nemačkejte prosím zbytečně. Spouští na serveru prostředkově náročnou operaci.</small>
<br>
<br>
<br>
<table>
    <tr>
        <th>Datum a čas</th>
        <th>Závažnost</th>
        <th>Zpráva</th>
        <th>Vyřešit</th>
    </tr>
    <?php foreach ($alerts as $alert) : ?>
        <tr class="alert-data-item" data-alert-id="<?= $alert->getId() ?>" style="background-color: #<?=
        ($alert->getLevel() === 'EMERGENCY') ? 'e9497b' :
            (($alert->getLevel() === 'ALERT') ? 'ff6666' :
                (($alert->getLevel() === 'CRITICAL') ? 'ff8080' :
                    (($alert->getLevel() === 'ERROR') ? 'ffa25b' : '999999')))
        ?>;">
            <td>
                <?= $alert->getTime() ?>
            </td>
            <td>
                <?= $alert->getLevel() ?>
            </td>
            <td>
                <?= $alert->getContent() ?>
            </td>
            <td>
                <button class='btn icon resolve-alert-button' title='Označit jako vyřešené'>
                    <img src='images/tick.svg' style="filter: sepia(1) brightness(1.5);"/>
                </button>
            </td>
        </tr>
    <?php endforeach ?>
</table>