<div id="info-text">
    <p>Jsi student, čeká tě poznávačka z biologie a není ti úplně jedno, jakou známku z ní dostaneš? Tak to by ti tahle webová aplikace mohla pomoct.</p>
    <p>Poznávačky - učiteli oblíbené, studenty většinou neoblíbené testy, při nichž je tvým úkolem poznat rostliny, živočichy či jiné organismy. Běžně je příprava na takový test zdlouhavá a ne úplně praktická, protože pokud se učíš podle prezentace, spíš než organismy se naučíš poznávat pouze konkrétní obrázky. Navíc si pak zapamatuješ i jejich pořadí a předem víš, že třeba po orangutanovi následuje šimpanz. Aplikace Poznávačky tyhle problémy řeší a snaží se ti učení co nejvíce usnadnit!</p>
    <p><i>I my, autoři aplikace, jsme totiž byli před pár lety v takové situaci, což nás motivovalo k jejímu vytvoření. Držíme se mindsetu "od studentů pro studenty" a stále se snažíme přidávat nové funkce, aby aplikace byla užitečnější.</i></p>
</div>

<div id="info-icons">
    <div class="img-wrapper"><img src="images/img1.svg" class="info-tile img-left" alt="Ikona registrace" ></div>
    <div id="new-class-info" class="info-tile">
        <h3>Založ si se spolužáky vlastní třídu</h3>
        <p>V rámci ní budeš moct vytvářet vlastní poznávačky podle toho, jak budeš potřebovat.</p>
    </div>
    <div class="img-wrapper"><img src="images/img2.svg" class="info-tile img-right" alt="Ikona přidávání obrázků"></div>
    <div id="add-pictures-info" class="info-tile">
        <h3>Přidávej k organismům obrázky</h3>
        <p>To může dělat každý ve třídě, a práce se tak rozloží. Navíc může být u každého organismu libovolný počet obrázků, takže se daný organismus naučíš mnohem lépe rozpoznat.</p>
    </div>
    <div class="img-wrapper"><img src="images/img3.svg" class="info-tile img-left" alt="Ikona učení"></div>
    <div id="learn-info" class="info-tile">
        <h3>Uč se</h3>
        <p>Organismy v poznávačkách si můžeš procházet a všímat si jejich charakteristických znaků.</p>
    </div>
    <div class="img-wrapper"><img src="images/img4.svg"class="info-tile img-right" alt="Ikona zkoušení"></div>
    <div id="test-info" class="info-tile">
        <h3>Otestuj, co ses naučil*a</h3>
        <p>Nech si vygenerovat test náhodných obrázků organismů a zjisti, jestli je už umíš poznat.</p>
    </div>
</div>