<p>Jsi student, čeká tě poznávačka z biologie a není ti úplně jedno, jakou známku z ní dostaneš? Tak to by ti tahle webová aplikace mohla pomoct. </p>
<p>Poznávačky - učiteli oblíbené, studenty většinou neoblíbené testy, při nichž je tvým úkolem poznat rostliny, živočichy či jiné organismy. Běžně je příprava na takový test zdlouhavá a ne úplně praktická, protože pokud se učíš podle prezentace, spíš než organismy se naučíš poznávat pouze konkrétní obrázky. Navíc si pak zapamatuješ i jejich pořadí a předem víš, že třeba po orangutanovi následuje šimpanz. Aplikace Poznávačky tyhle problémy řeší, a navíc je zcela zdarma! A to se, Horste, vyplatí!
<div id="info-icons">
    <div id="new-class-info" class="info-tile">
        <img src="../images/register.svg" alt="">
        <h3>Založ si se spolužáky vlastní třídu</h3>
        <p>V rámci ní budeš moct vytvářet vlastní poznávačky podle toho, jak budeš potřebovat.</h3>
    </div>
    <div id="add-pictures-info" class="info-tile">
        <img src="../images/add-pictures.svg" alt="">
        <h3>Přidávej k jednotlivým organismům obrázky</h3>
        <p>To může dělat každý ve třídě, a práce se tak rozloží. Navíc může být u každého organismu libovolný počet obrázků, takže se daný organismus naučíš mnohem lépe rozpoznat.</p>
    </div>
    <div id="learn-info" class="info-tile">
        <img src="../images/learn.svg" alt="">
        <h3>Uč se</h3>
        <p>Organismy v poznávačkách si můžeš procházet a všímat si jejich charakteristických znaků.</p>
    </div>
    <div id="test-info" class="info-tile">
        <img src="../images/test.svg" alt="">
        <h3>Otestuj, co ses naučil</h3>
        <p>Nech si vygenerovat test náhodných obrázků organismů a zjisti, jestli je už umíš poznat.</p>
    </div>
</div>