<div id="temp-data" style="display:none;">
    <pre id="group-urls-json"><?= json_encode($groupList); ?></pre>
    <pre id="natural-names-json"><?= json_encode($naturalList); ?></pre>
</div>
<section class="info-section" style="display: none">
    <h3>Nápověda</h3>
    <p>Na této stránce můžeš spravovat přírodniny, které ve tvé třídě existují.</p>
    <ul class="list">
        <li>Název poznávačky musí být jedinečný. Název části musí být jedinečný v rámci dané poznávačky.</li>
        <li>Odebráním části nebudou smazány žádné přírodniny ani obrázky k nim nahrané. Přírodniny, které jsou do takovýchto částí přiřazeny, zůstanou dostupné a budete je moci později přiřadit do jiných částí a poznávaček.</li>
        <li>V jedné části se nesmí stejná přírodnina vyskytovat vícekrát. Může se ale vyskytovat vícekrát v různých částech nebo v různých poznávačkách.</li>
        <li>Pokud do některé části přidáš přírodninu, která už se ve tvé třídě nachází, bude automaticky propojena s již existujícími obrázky, které k ní patří.</li>
        <li>Pokud při úpravách uděláš chybu (například odebereš část, která obsahuje velké množství přírodnin), můžeš poznávačku navrátit do původního stavu kliknutím na tlačítko <i>Zahodit změny</i>. Žádné změny nebudou trvale uloženy, dokud neklikneš na tlačítko <i>Uložit</i>. Nezapomeň si proto změny, o které nechceš přijít, průběžně ukládat.</li>
    </ul>
</section>
<div id="edit-group-wrapper">
    <div id="group-name-container">
        <div class="group name-box">
            <span class="group name"><?= $groupName ?></span>
            <button class="rename-group-button btn icon" title="Přejmenovat">
                <img src='images/pencil-black.svg' alt="Přejmenovat">
            </button>
        </div>
        <div class="group name-input-box" style="display:none;">
            <input type="text" maxlength="31" size="1" class="text-field group-name-input" value="<?= $groupName ?>"/>
            <button class="rename-group-confirm-button btn icon" title="Potvrdit">
                <img src='images/tick.svg' alt="Potvrdit">
            </button>
            <button class="rename-group-cancel-button btn icon" title="Zrušit">
                <img src='images/cross-thick-black.svg' alt="Zrušit">
            </button>
        </div>
    </div>
    <div id="parts-boxes-container">
        <?php foreach ($parts as $part) : ?>
        <div class="part box">
            <div class="part info">
                <button class="remove-part-button btn icon" title="Odebrat část">
                    <img src='images/cross-thin-black.svg' alt="Odebrat část">
                </button>
                <div class="part name-box">
                    <span class="part name"><?= $part->getName() ?></span>
                    <button class="rename-part-button btn icon" title="Přejmenovat">
                        <img src='images/pencil-black.svg' alt="Přejmenovat">
                    </button>
                </div>
                <div class="part name-input-box" style="display:none;">
                    <input type="text" maxlength="31" size="1" class="text-field part name-input" value="<?= $part->getName() ?>"/>
                    <button class="rename-part-confirm-button btn icon" title="Potvrdit">
                        <img src='images/tick.svg' alt="Potvrdit">
                    </button>
                    <button class="rename-part-cancel-button btn icon" title="Zrušit">
                        <img src='images/cross-thick-black.svg' alt="Zrušit">
                    </button>
                </div>
                <div class="add-natural">
                    <label>Přírodnina k přidání</label>
                    <input type="text" class="text-field new-natural-name-input"/>
                    <button class="new-natural-button btn border-btn non-transparent black">Přidat</button>
                </div>
            </div>
            <ul class="naturals-in-part">
                <?php foreach ($part->getNaturals() as $natural) : ?>
                <li>
                    <div class="natural name-box">
                        <span class="natural name"><?= $natural->getName() ?></span>
                        <button class="remove-natural-button btn icon" title="Odebrat">
                            <img src='images/cross-thin-black.svg' alt="Odebrat">
                        </button>
                        <button class="rename-natural-button btn icon" title="Přejmenovat" style="display:none;">
                            <img src='images/pencil-black.svg' alt="Přejmenovat">
                        </button>
                    </div>
                    <div class="natural name-input-box" style="display:none;">
                        <input type="text" maxlength="31" class="text-field natural name-input" value="<?= $natural->getName() ?>"/>
                        <button class="rename-natural-confirm-button btn icon" title="Potvrdit">
                            <img src='images/tick.svg' alt="Potvrdit">
                        </button>
                        <button class="rename-natural-cancel-button btn icon" title="Zrušit">
                            <img src='images/cross-thick-black.svg' alt="Zrušit">
                        </button>
                    </div>
                </li>
                <?php endforeach ?>
            </ul>
        </div>
        <?php endforeach ?>
        <div id="add-part-button" class="btn">
            <img src="images/plus-black.svg" alt="Plus">
            <div>Přidat novou část</div>
        </div>
    </div>
    <div id="submit-buttons-wrapper">
        <button id="edit-cancel-button" class="btn border-btn transparent black">Zahodit změny</button>
        <button id="edit-submit-button" class="btn border-btn non-transparent black">Uložit změny</button>
    </div>
</div>


<div id="part-box-template" class="data-item-template" style="display: none">
    <div class="part box">
        <div class="part info">
            <button class="remove-part-button btn icon" title="Odebrat část">
                <img src='images/cross-thin-black.svg' alt="Odebrat část">
            </button>
            <div class="part name-box" style="display: none">
                <span class="part name"></span>
                <button class="rename-part-button btn icon" title="Přejmenovat">
                    <img src='images/pencil-black.svg' alt="Přejmenovat">
                </button>
            </div>
            <div class="part name-input-box">
                <input type="text" maxlength="31" size="1" class="text-field part name-input" value=""/>
                <button class="rename-part-confirm-button btn icon" title="Potvrdit">
                    <img src='images/tick.svg' alt="Potvrdit">
                </button>
                <button class="rename-part-cancel-button btn icon" title="Zrušit" style="display: none">
                    <img src='images/cross-thick-black.svg' alt="Zrušit">
                </button>
            </div>
            <div class="add-natural">
                <label>Přírodnina k přidání</label>
                <input type="text" class="text-field new-natural-name-input"/>
                <button class="new-natural-button btn border-btn non-transparent black">Přidat</button>
            </div>
        </div>
        <ul class="naturals-in-part">
        </ul>
    </div>
</div>


<div id="natural-template" class="data-item-template" style="display: none">
    <li>
        <div class="natural name-box">
            <span class="natural name"></span>
            <button class="remove-natural-button btn icon" title="Odebrat">
                <img src='images/cross-thin-black.svg' alt="Odebrat">
            </button>
            <button class="rename-natural-button btn icon" title="Přejmenovat">
                <img src='images/pencil-black.svg' alt="Přejmenovat">
            </button>
        </div>
        <div class="natural name-input-box" style="display:none;">
            <input type="text" maxlength="31" class="text-field natural name-input" value=""/>
            <button class="rename-natural-confirm-button btn icon" title="Potvrdit">
                <img src='images/tick.svg' alt="Potvrdit">
            </button>
            <button class="rename-natural-cancel-button btn icon" title="Zrušit">
                <img src='images/cross-thick-black.svg'>
        </div>
    </li>
</div>
