<div id="temp-data" style="display:none;">
	<pre id="group-urls-json"><?= json_encode($groupList); ?></pre>
	<pre id="natural-names-json"><?= json_encode($naturalList); ?></pre>
</div>
<div id="edit-group-wrapper">
	<!--
	<div id="help-container">
		<button title="Nápověda" id="help-button" class="btn icon">
			<img src='images/info.svg'/>
		</button>
		<div id="help-text" style="display:none">
			<p>
				Vítejte v rozhraní pro editaci poznávačky. Na této stránce můžete vybranou poznávačku přejmenovat,
				přidávat či odebírat z ní části a přejmenovávat i je. A samozřejmě můžete do těchto částí přidávat
				přírodniny.
			</p>
			<p>
				Při přejmenovávání poznávačky dávejte pozor, abyste nezvolili jméno, které už má nějaká z jiných
				poznávaček patřících do vaší třídy. V případě konfliktu budete okamžitě upozorněni. To samé se týká jmen
				částí, také musí být unikátní, avšak můžete mít v různých poznávačkách části se stejnými jmény.
			</p>
			<p>
				Odebráním části nebudou smazány žádné přírodniny ani obrázky k nim nahrané. Přírodniny, které jsou do
				takovýchto částí přiřazeny zůstanou dostupné a budete je moci později přiřadit do jiných částí a
				poznávaček.
			</p>
			<p>
				Každou přírodninu můžete přidat do více různých poznávaček a dokonce ji můžete mít i vícekrát v různých
				částech tétož poznávačky. Jediným pravidlem je, že tatáž přírodnina se nesmí vícekrát vyskytovat ve
				stejné části.
			</p>
			<p>
				Při přidávání přírodnin se vám budou automaticky nabízet přírodniny, které již ve vaší třídě existují.
				Pokud některou z existujících přírodnin vyberete, budou v této poznávačce rovnou dostupné i všechny
				obrázky, které k ní byly přidány v jiných poznávačkách. Funguje to i obráceně – pokud k dané přírodnině
				v této poznávačce někdo přidá obrázek, bude tento obrázek zobrazován i ve všech ostatních poznávačkách
				používajících danou přírodninu.
			</p>
			<p>
				Pokud pro přidání zvolíte přírodninu, která zatím neexistuje, bude po uložení změn vytvořena. Takováto
				přírodnina bude nejprve bez obrázků, ale to se změní s prvním přidaným obrázkem. Nově vytvořené
				přírodniny mohou být také použity v ostatních poznávačkách.
			</p>
			<p>
				Pokud při úpravách uděláte chybu, například že odeberete část, která obsahuje velké množství přírodnin,
				můžete poznávačku navrátit do původního stavu aktualizací stránky. Žádné změny nebudou trvale uloženy,
				dokud nekliknete na tlačítko "Uložit" v dolní části stránky. Nezapomeňte si proto změny průběžné
				ukládat.
			</p>
		</div>
	</div>
	-->
	<div id="group-name-container">
		<div class="group-name-box">
			<span class="group-name"><?= $groupName ?></span>
			<button title="Přejmenovat poznávačku" class="rename-group btn icon">
				<img src='images/pencil.svg'/>
			</button>
		</div>
		<div class="group-name-input-box" style="display:none;">
			<input type="text" maxlength="31" class="text-field group-name-input" value="<?= $groupName ?>"/>
			<button class="rename-group-confirm btn icon">
				<img src='images/tick.svg'/>
			</button>
			<button class="rename-group-cancel btn icon">
				<img src='images/cross.svg'/>
			</button>
		</div>
		<div class="group-name-url">V URL bude zobrazováno jako <?= $groupUrl ?></div>
	</div>
	<div id="parts-boxes-container">
		<?php foreach ($parts as $part) : ?>
		<div class="part-box">
			<div class="part-info">
				<button title="Odebrat část" class="remove-part btn icon" title="Odebrat část">
					<img src='images/cross.svg'/>
				</button>
				<div class="part-name-box">
					<span class="part-name"><?= $part->getName() ?></span>
					<button title="Přejmenovat část" class="rename-part btn icon">
						<img src='images/pencil.svg'/>
					</button>
				</div>
				<div class="part-name-input-box" style="display:none;">
					<input type="text" maxlength="31" class="text-field part-name-input" value="<?= $part->getName() ?>"/>
					<button class="rename-part-confirm btn icon">
						<img src='images/tick.svg'/>
					</button>
					<button class="rename-part-cancel btn icon">
						<img src='images/cross.svg'/>
					</button>
				</div>
				<div class="part-name-url">V URL bude zobrazováno jako <?= $part->getUrl() ?></div>
				<label>
					<span>Přírodnina k přidání</span>
					<input type="text" class="text-field new-natural-name-input"/>
					<button class="new-natural-button btn border-btn non-transparent black">Přidat</button>
				</label>
				<!--<select class="new-natural-name-suggestions"></select> TODO nahradit při stylování vhodnějším prvkem -->
			</div>
			<ul class="naturals-in-part">
				<?php foreach ($part->getNaturals() as $natural) : ?>
				<li>
					<div class="natural-name-box">
						<span class="natural-name"><?= $natural->getName() ?></span>
						<button title="Odebrat" class="remove-natural btn icon">
							<img src='images/cross.svg'/>
						</button>
						<button title="Přejmenovat" class="rename-natural btn icon" style="display:none;">
							<img src='images/pencil.svg'/>
						</button>
					</div>
					<div class="natural-name-input-box" style="display:none;">
						<input type="text" maxlength="31" class="text-field natural-name-input" value="<?= $natural->getName() ?>"/>
						<button class="rename-natural-confirm btn icon">
							<img src='images/tick.svg'/>
						</button>
						<button class="rename-natural-cancel btn icon">
							<img src='images/cross.svg'/>
						</button>
					</div>
				</li>
				<?php endforeach ?>
			</ul>
		</div>
		<?php endforeach ?>
	</div>
	<button id="add-part-button" class="btn border-btn non-transparent black">Přidat novou část</button>
	<div id="submit-wrapper">
		<button id="submit" class="btn border-btn non-transparent black">Uložit změny</button>
	</div>
</div>


<div id="part-box-template" style="display: none">
	<div class="part-box">
		<div class="part-info">
			<button title="Odebrat část" class="remove-part btn icon" title="Odebrat část">
				<img src='images/cross.svg'/>
			</button>
			<div class="part-name-box" style="display: none">
				<span class="part-name"></span>
				<button title="Přejmenovat část" class="rename-part btn icon">
					<img src='images/pencil.svg'/>
				</button>
			</div>
			<div class="part-name-input-box">
				<input type="text" maxlength="31" class="text-field part-name-input" value=""/>
				<button class="rename-part-confirm btn icon">
					<img src='images/tick.svg'/>
				</button>
				<button class="rename-part-cancel btn icon" style="display: none">
					<img src='images/cross.svg'/>
				</button>
			</div>
			<!-- part-name-box a part-name-input-box zabalit?, editnout i nahoře + js -->
			<div class="part-name-url">V URL bude zobrazováno jako </div>
			<label>
				<span>Přírodnina k přidání</span>
				<input type="text" class="text-field new-natural-name-input"/>
				<button class="new-natural-button btn border-btn non-transparent black">Přidat</button>
			</label>
		</div>
		<!--<select class="new-natural-name-suggestions"></select> TODO nahradit při stylování vhodnějším prvkem -->
		<ul class="naturals-in-part">
		</ul>
	</div>
</div>


<div id="natural-item-template" style="display: none">
	<li>
		<div class="natural-name-box">
			<span class="natural-name"></span>
			<button title="Odebrat" class="remove-natural btn icon">
				<img src='images/cross.svg'/>
			</button>
			<button title="Přejmenovat" class="rename-natural btn icon">
				<img src='images/pencil.svg'/>
			</button>
		</div>
		<div class="natural-name-input-box" style="display:none;">
			<input type="text" maxlength="31" class="text-field natural-name-input" value=""/>
			<button class="rename-natural-confirm btn icon">
				<img src='images/tick.svg'/>
			</button>
			<button class="rename-natural-cancel btn icon">
				<img src='images/cross.svg'/>
			</button>
		</div>
	</li>
</div>
