<div id="email">
    <div id="email-info">
        <label for="email-sender">Odesílatel:</label>
        <input id="email-sender" type=text maxlength=255 value="<?= $loggedAdminName ?>" />
        <label for="email-sender-address">Adresa pro odpověď:</label>
        <input id="email-sender-address" type=email maxlength=255 value="poznavacky@email.com" />
        <label for="email-address">Adresát:</label>
        <input id="email-address" type=email maxlength=255 />
        <label for="email-subject">Předmět:</label>
        <input id="email-subject" type=text maxlength=70 />
    </div>
    <div id="email-editor">
        <label for="email-message">Zpráva</label>
        <textarea id="email-message"></textarea>
        <label for="email-footer">Zápatí</label>
        <textarea id="email-footer">Tato zpráva nebyla vygenerována automaticky</textarea>
    </div>
    <div id="email-preview" style="display:none;"> <!-- Zde se zobrazí náhled e-mailu --> </div>
    <button id="preview-email-button" class="btn border-btn">Zobrazit náhled</button>
    <button id="edit-email-button" class="btn border-btn" style="display:none">Upravit zprávu</button>
    <button id="send-email-button" class="btn border-btn">Odeslat</button>
    <span id="status-info" style="display: none">E-mail se odesílá...</span>
    <div>Obrázky se v náhledu nezobrazují správně.</div>
</div>