<img src="images/error.png" id="errorPic"/>
<main>
	<h1>HTTP CHYBA <span id="code">403</span></h1>
	<br><br><br><br><br><br>
	<span>Nemáte oprávnění k přístupu k tomuto souboru nebo adresáři. To může být způsobeno například vypršením vašeho přihlášení.</span>
	<br><br><br><br><br><br>
	<span id="listHeader">Navrhované akce:</span>
	<br><br>
	<ul>
		<li>Vraťte se na <a href="/">domovskou stránku</a></li>
		<li>Kontaktujte <a href="mailto:<?= $_SERVER['SERVER_ADMIN'] ?>">správce</a></li>
		<li>Zkuste to znovu později</li>
	</ul>
</main>