<img src="images/error.png" id="errorPic"/>
<main>
    <h1>HTTP CHYBA <span id="code">404</span></h1>
    <br><br><br><br><br><br>
    <span>Vámi požadovaná URL adresa nemohla být na serveru nalezena.</span>
    <br><br><br><br><br><br>
    <span id="listHeader">Navrhované akce:</span>
    <br><br>
    <ul>
        <li>Vraťte se na <a href="/">domovskou stránku</a></li>
        <li>Zkontrolujte, zda nemáte v adrese URL chybu.</li>
        <li>Kontaktujte <a href="mailto:<?= $_SERVER['SERVER_ADMIN'] ?>">správce</a></li>
        <li>Zkuste to znovu později</li>
    </ul>
</main>