<header>
    <img src="images/error.svg" class="error-img"/>
    <h1>HTTP CHYBA <span class="error-code">403</span></h1>
</header>
<main>
    <p>Nemáte oprávnění k přístupu k tomuto souboru nebo adresáři. To může být způsobeno například vypršením vašeho přihlášení.</p>
    <h2>Navrhované akce</h2>
    <ul class="list">
        <li>Vraťte se na <a class="btn inline black" href="/">domovskou stránku</a></li>
        <li>Kontaktujte <a class="btn inline black" href="mailto:<?= $_SERVER['SERVER_ADMIN'] ?>">správce</a></li>
        <li>Zkuste to znovu později</li>
    </ul>
</main>