<header>
	<img src="images/error.png" class="error-img"/>
	<h1>HTTP CHYBA <span class="error-code">403</span></h1>
</header>
<main>
    <p>Vámi požadovaná URL adresa nemohla být na serveru nalezena.</p>
    <h2>Navrhované akce</h2>
    <ul>
        <li>Vraťte se na <a href="/">domovskou stránku</a></li>
        <li>Zkontrolujte, zda nemáte v adrese URL chybu.</li>
        <li>Kontaktujte <a href="mailto:<?= $_SERVER['SERVER_ADMIN'] ?>">správce</a></li>
        <li>Zkuste to znovu později</li>
    </ul>
</main>