<!DOCTYPE HTML>
<html lang="cs">
    <head>
        <base href="/" />
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width" />
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keywords ?>" />
        <!-- Ikony -->
        <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="images/safari-pinned-tab.svg" color="#479911">
        <link rel="shortcut icon" href="images/favicon.ico">
        <meta name="msapplication-TileColor" content="#366e11">
        <meta name="msapplication-config" content="browserconfig.xml">
        <meta name="theme-color" content="#366e11">
        
        <!-- Styly -->
        <?php foreach ($cssFiles as $cssFile) : ?>
            <link rel="stylesheet" type="text/css" href="<?= $cssFile ?>">
        <?php endforeach ?>
    </head>
    <body id="<?= $bodyId ?>">
        <div id="overlay"></div>
        <div id="popups"></div>
        <div class="container">
            <?php require $this->getNextView(); ?>
            <div id="messages">
                <?php foreach ($messages as $messageBox) : ?>
                    <div class="message-item <?= $messageBox['messageClass'] ?>">
                        <span class="message"><?= $messageBox['message'] ?></span>
                        <button class="btn icon close-message-button" title="Zavřít"><img class="icon white" src="images/cross-thick.svg" alt="Zavřít"></button>    
                    </div>
                <?php endforeach ?>
            </div>
            <footer>
                <div class="content">
                    <a id="help" class="btn inline" target='_blank' rel="noopener" href="https://github.com/ShadyMedic/Poznavacky/wiki">Nápověda</a>
                    <a id="issues" class="btn inline" onclick="showLogin()" rel="noopener" target='_blank' href="https://forms.gle/sreDqmdtNT4Z3jwr5">Nalezl*a jsi problém?</a>
                    <a id="terms" class="btn inline" target='_blank' rel="noopener" href='/legal'>Právní informace</a>
                    <span id="about">&copy Štěchy a Eksyska, <?= $currentYear ?></span>
                </div>
            </footer>
        </div>
        <div id="message-item-template" style="display: none">
            <div class="message-item">
                <div class="text">
                    <p class="message"></p>
                    <p class="data"></p>
                </div>
                <button class="btn icon close-message-button" title="Zavřít"><img class="icon white" src="images/cross-thick.svg" alt="Zavřít"></button>
            </div>
        </div>
        <div id="confirm-item-template" style="display: none">
            <div tabindex="-1" class="confirm-item form">
                <div class="text">
                    <p class="message"></p>
                </div>
                <div class="buttons">
                    <button class="btn border-btn non-transparent black confirm-popup-button submit-button"></button>
                    <button class="btn border-btn transparent black cancel-popup-button cancel-button"></button>
                </div>
            </div>
        </div>
        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <!-- JavaScript -->
        <?php foreach ($jsFiles as $jsFile) : ?>
            <script type="text/javascript" src="<?= $jsFile ?>"></script>
        <?php endforeach ?>
    </body>
</html>