<!DOCTYPE HTML>
<html>
    <head>
        <base href="/" />
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width" />
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keywords ?>" />
        <!-- Ikony -->
        <link rel="icon" href="images/favicon.ico">
        <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="images/icon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="images/icon-16x16.png">
        <link rel="manifest" href="manifest.json">
        <link rel="mask-icon" href="images/safari-pinned-tab.svg" color="#ffc835">
        <meta name="theme-color" content="#ffffff">
        <!-- Styly -->
        <link rel="stylesheet" type="text/css" href="<?= $cssFile ?>">
        <!-- JavaScript -->
        <script type="text/javascript" src="<?= $jsFile?>"></script>
    </head>
    <body id="<?= ?>"> <!-- DOPNĚNÍ ID -->
        <?php $this->controllerToCall->displayView(); ?>
		<footer>
			<a id="help" class="footer-option" target='_blank' href="https://github.com/HonzaSTECH/Poznavacky/wiki">Nápověda</a>
			<a id="issues" class="footer-option" onclick="showLogin()" target='_blank' href="https://github.com/HonzaSTECH/Poznavacky/issues/new/choose">Nalezli jste problém?</a>
			<a id="terms" class="footer-option" target='_blank' href='https://github.com/HonzaSTECH/Poznavacky/blob/master/documents/TERMS_OF_SERVICE.md'>Podmínky služby</a>
			<span id="about" class="footer-option">&copy Štěchy a Eksyska, <?= ?> <!-- AUTOMATICKÁ AKTUALIZACE ROKU --></span>
			<!--<script>
				function showLogin()
				{
					alert("Přihlašovací údaje pro nahlašování chyby:\nJméno: gjvj\nHeslo: poznavacky71");
				}
			</script>--> <!-- BUDE PŘEDĚLÁNO -->
		</footer>
	</body>
</html>