<!--<div id="background"></div>
<div id="background-overlay"></div>-->
<header>
	<div class="content">
		<button class="btn inline white show-login-section-login-button">Přihlásit se</button>
		<button class="btn inline white show-login-section-register-button">Zaregistrovat se</button>
	</div>
</header>
<main>
	<section id="index-text-section">
		<div class="content">
			<h1>Poznávačky</h1>
			<p>Potřebujete se naučit, jak rozeznat různé rostliny, živočichy nebo jiné organismy? Zaregistrujte se, vytvořte si seznam přírodnin, sdílejte ho se svou třídou a učte se rychleji!</p>
			<a href="#index-info-section"><button class="btn arrow-btn black"><span>Zjistit více</span><img src="../images/arrowBlack.svg"></button></a>
		</div>
		<img src="../images/leafGuyLight.svg">
	</section>
	<section id="index-buttons-section">
		<div class="content">
			<button class="btn border-btn rounded non-transparent white show-login-section-register-button">Zaregistrovat se</button>
			<button class="btn border-btn rounded non-transparent white show-login-section-login-button">Přihlásit se</button>
			<button class="btn border-btn rounded transparent white" id="demo-button">Vyzkoušet demo</button>
		</div>
	</section>
	<section id="index-login-section">
		<div class="button-wrapper">
			<button id="hide-login-section-button" class="btn icon cross" id="hide-login-section-button"><img src="../images/cross2black.svg" alt="Zavřít"></button>
		</div>	
		<div id="login">
			<h2>Přihlašte se</h2>
			<form id="login-form">
				<div class="user-data">
					<input id='login-hidden' type='hidden' name='type' value='l'>
					<label for='login-name'>Jméno</label>
					<input id='login-name' class="text-field" type='text' name='loginName' maxlength=15>
					<div id="login-name-message" class="message"></div>
					<label for='login-pass'>Heslo</label>
					<input id='login-pass' class="text-field" type='password' name='loginPass' maxlength=31>
					<div id="login-pass-message" class="message"></div>
					<label class="custom-checkbox-wrapper">Zůstat přihlášen
						<input id="login-persist" type="checkbox" name='stay_logged'/>
						<span class="checkmark"></span>
					</label>
				</div>
				<button id='login-submit' class="btn border-btn center non-transparent black">Přihlásit se</button>
				<div id="login-server-message" class="message"></div>
			</form>
			<p><button class="btn inline black show-login-section-password-recovery-button">Zapomněli jste heslo?</button></p>
			<p>Ještě nemáte účet? <button class="btn inline black show-login-section-register-button">Zaregistrujte se</button>.</p>
		</div>
		<div id="register">
			<h2><img src="../images/icon-192.png">Zaregistrujte se</h2>
			<form id="register-form">
				<div class="user-data">
					<input id='register-hidden' type='hidden' name='type' value='r'>
					<label for="register-name" class="required">Jméno</label>
					<input id='register-name' class="text-field" type='text' name='registerName' maxlength=15>
					<div id="register-name-message" class="message"></div>
					<label for="register-pass" class="required">Heslo</label>
					<input id='register-pass' class="text-field" type='password' name='registerPass' maxlength=31>	
					<div id="register-pass-message" class="message"></div>
					<label for="register-repass" class="required">Heslo znovu</label>
					<input id='register-repass' class="text-field" type='password' name='registerRepass' maxlength=31>
					<div id="register-repass-message" class="message"></div>
					<label for="register-email">E-mail</label>
					<input id='register-email' class="text-field" type='text' name='registerEmail' maxlength=255>
					<div id="register-email-message" class="message"></div>
				</div>
				<p id='terms'>Registrací souhlasíte s <a class="btn inline black" target='_blank' href='https://github.com/HonzaSTECH/Poznavacky/blob/master/documents/TERMS_OF_SERVICE.md'>podmínkami služby</a>.</p>
				<button id='register-submit' class="btn border-btn center non-transparent black">Vytvořit účet</button>
				<div id="register-server-message" class="message"></div>
			</form>
			<p>Již máte účet? <button class="btn inline black show-login-section-login-button" onclick="showLoginDiv('login')">Přihlašte se</button>.</p>
		</div>
		<div id="password-recovery">
			<p>Zadejte svoji e-mailovou adresu. Pokud existuje účet s takovou přidruženou adresou, pošleme na něj e-mail s instrukcemi k obnově hesla.</p>
			<form id="pass-recovery-form">
				<div class="user-data">
					<input id='password-recovery-hidden' type='hidden' name='type' value='p'>
					<input id='password-recovery-email' class="text-field" name="passRecoveryEmail" maxlength=255 />
					<div id="password-recovery-email-message" class="message"></div>
				</div>
				<button id='password-recovery-submit' class="btn border-btn center non-transparent black">Odeslat</button>
				<div id="password-recovery-server-message" class="message"></div>
			</form>
			<p>Nepamatujete si, jakou jste zadávali při registraci e-mailovou adresu, nebo jste žádnou nezadávali? Napište nám na <i style="font-style: italic;">poznavacky@email.com</i> a my vám pomůžeme obnovit heslo jinou metodou.</p>
			<button class="btn inline black show-login-section-login-button">Zpět</button>
		</div>
	</section>
	<section id="index-info-section">
		<?php require 'Views/appInfo.phtml'; ?>
	</section>
</main>
<div id="cookies-alert">
	<span>Tyto stránky využívají ke své funkci soubory cookie. Používáním stránek souhlasíte s ukládáním souborů cookie na vašem zařízení.</span>
	<button id="hide-cookies-alert-button" class="btn cross"><img src="..\images\crossButtonWhite.svg"></button>
</div>
<a id="back-to-top" class="btn border-btn rounded non-transparent white" href="#index"><img src="../images/arrowsUp.svg"></a>