<header>
	<h1>Poznávačky</h1>
</header>
<main>
	<section id="index-text-section">
		<p>Potřebujete se naučit, jak rozeznat různé rostliny, živočichy nebo jiné organismy? Zaregistrujte se, vytvořte si seznam přírodnin, sdílejte ho se svou třídou a učte se rychleji!</p>
		<button>Zjistit více</button>
	</section>
	<section id="index-buttons-section">
		<button>Zaregistrovat se</button>
		<button>Přihlásit se</button>
		<button>Vyzkoušet demo</button>
	</section>
	<section id="login-section">
		<div id="login">
			<h2>Přihlašte se</h2>
			<form method="POST" action="index-forms">
				<input id='login-hidden' type='hidden' name='type' value='l'>
				<input id='login-name' type='text' name='name_input' maxlength=15 placeholder='Jméno'>
				<input id='login-pass' type='password' name='pass_input' maxlength=31 placeholder='Heslo'>
				<div class="checkbox">
					<input type="checkbox" name='stay_logged'/>
					<label for="login_keep">Zůstat přihlášen</label>
				</div>
				<button id='login-submit' onclick='login()'>Přihlásit se</button>
			</form>
			<span><a href="javascript:showPasswordRecovery()">Zapomněli jste heslo?</a></span>
			<span>Ještě nemáte účet? <a href="javascript:showRegister()">Zaregistrujte se</a>.</span>
			<div id="login-errors">
				<?= $loginError ?>
			</div>
		</div>
		<div id="register">
			<h2>Zaregistrujte se</h2>
			<form method="POST" action="index-forms">
				<input id='register-hidden' type='hidden' name='type' value='r'>
				<input id='register-name' type='text' name='name_input' maxlength=15 placeholder='Jméno' required=true>
				<input id='register-pass' type='password' name='pass_input' maxlength=31 placeholder='Heslo' required=true> 				    	
				<input id='register-repass' type='password' name='repass_input' maxlength=31 placeholder='Heslo znovu' required=true>
				<input id='register-email' type='email' name='email_input' maxlength=255 placeholder='E-mail (nepovinné)'>
				<span id='span-terms'>Registrací souhlasíte s <a target='_blank' href='https://github.com/HonzaSTECH/Poznavacky/blob/master/documents/TERMS_OF_SERVICE.md'>podmínkami služby</a>.</span>
				<button id='register-submit' onclick='register()'>Vytvořit účet</button>
			</form>
			<span>Již máte účet? <a href="javascript:showLogin()">Přihlašte se</a>.</span>
			<div id="register-errors">
				<?= $registerError ?>
			</div>
		</div>
		<div id="password-recovery">
			<span>Zadejte svoji e-mailovou adresu. Pokud existuje účet s takovou přidruženou adresou, pošleme na něj e-mail s instrukcemi k obnově hesla.</span>
			<form method="POST" action="index-forms">
				<input id='password-recovery-hidden' type='hidden' name='type' value='p'>
				<input id='password-recovery-input' type=text name="email_input" maxlength=255 required=true />
				<button id='password-recovery-submit' onclick="recoverPassword()">Odeslat</button> 
			</form>
			<span>Nepamatujete si, jakou jste zadávali při registraci e-mailovou adresu, nebo jste žádnou nezadávali? Napište nám na <i style="font-style: italic;">poznavacky@email.com</i> a my vám pomůžeme obnovit heslo jinou metodou.</span>
			<button onclick="showLogin()">Zpět</button>
			<div id='password-recovery-errors'>
				<?= $passRecoveryError ?>
			</div>
		</div>
	</section>
</main>
<div id="cookies-alert">
	<span>Tyto stránky využívají ke své funkci soubory cookie. Používáním stránek souhlasíte s ukládáním souborů cookie na vašem zařízení.</span>
	<span id="cookies-alert-closer" onclick="hideCookies()">x</span>
</div>