<h2>Učit se</h2>
<div id="key-navigation-wrapper" tabindex="-1">
<section>
	<select id="select-box" onchange="sel()">
	<?php foreach ($naturals as $natural) : ?>
        <option><?= $natural->getName() ?></option>
	<?php endforeach; ?>
	</select>
	<button id="natural-back-button" class="button">
		Předchozí přírodnina
		<span class="key-short">[S]</span>
	</button>
		<button id="natural-forward-button" class="button">
		Následující přírodnina
		<span class="key-short">[W]</span>
	</button>
</section>
<section>
	<button id="picture-back-button">
		<img src="images/arrow.png" style="transform: rotate(180deg);" />
		<span>[A]</span>
	</button>
	<img id="main-img" src="images/imagePreview.png"> <!-- Adresa bude dodána JavaScriptem -->
	<button id="picture-forward-button">
		<img src="images/arrow.png" />
		<span>[D]</span>
	</button>
	<div>
		<?php require 'Views/reportForm.phtml'; ?>
	</div>
</section>
</div>