<h2>Učit se</h2>
<section>
	<select id="selectBox" onchange="sel()">
	<?php foreach ($naturals as $natural) : ?>
        <option><?= $natural->getName() ?></option>
	<?php endforeach; ?>
	</select>
</section>
<section>
	<button onclick="updatePicture(-1)">
		<img src="images/arrow.png" style="transform: rotate(180deg);" />
		<span>[A]</span>
	</button>
	<img id="mainImg" src="images/imagePreview.png"> <!-- Adresa bude dodána JavaScriptem -->
	<button onclick="updatePicture(1)">
		<img src="images/arrow.png" />
		<span>[D]</span>
	</button>
	<button onclick="reportImg(event)"></button>
	<div>
		<?php require 'Views/reportForm.phtml'; ?>
	</div>
</section>