<header>
	<div class="logo">
		<!-- <img src="">  LOGO -->
		<h1>Poznávačky</h1>
	</div>
</header>
<main>
	<nav>
		<button id="tos-button" class="btn border-btn transparent white">Podmínky služby</button>
		<button id="pp-button" class="btn border-btn transparent white">Zásady ochrany soukromí</button>
		<button id="cookies-button" class="btn border-btn transparent white">Využívání souborů cookies</button>
	</nav>

	<div class="content">
		<section id="tos">
			<?php require 'staticArticle.phtml' ?>
		</section>
		<section id="pp">
			<?php require 'staticArticle.phtml' ?>
		</section>
		<section id="cookies">
			<?php require 'staticArticle.phtml' ?>
		</section>
	</div>
</main>
