<div id="logo-standalone">
    <img src="images/icon-white.svg" alt="Logo Poznávaček">
</div>
<header>
</header>
<main>
    <nav>
        <button id="tos-button" class="btn inline black">Podmínky služby</button>
        <button id="pp-button" class="btn inline black">Zásady ochrany soukromí</button>
        <button id="cookies-button" class="btn inline black">Využívání souborů cookies</button>
    </nav>
    <div class="content">
        <section id="tos">
            <?php require 'staticArticle.phtml' ?>
        </section>
        <section id="pp">
            <?php require 'staticArticle.phtml' ?>
        </section>
        <section id="cookies">
            <?php require 'staticArticle.phtml' ?>
        </section>
    </div>
</main>
