<?php $this->controllerToCall->displayView(); ?>
<button onclick="window.location.href='<?= $returnButtonLink ?>'">Zpět</button>

<style>
/* Toto je pouze dočasné stylování, odstraň jej, nebo jej přesuň do .css souboru */
.actionButton {
    height: 1.2em;
    width: 1.2em;
    position: relative;
    top: -0.08rem;
    padding: 0;
    vertical-align: middle;
    background: none;
}
.actionButton img {

    object-fit: contain;
}
.testEditorNaturalRow
{
    display: none;
}
</style>
