<style>
/* Toto je pouze dočasné stylování, odstraň jej, nebo jej přesuň do .css souboru */
.actionButton {
    height: 1.2em;
    width: 1.2em;
    position: relative;
    top: -0.08rem;
    padding: 0;
    vertical-align: middle;
    background: none;
}
.actionButton img {

    object-fit: contain;
}
.testEditorNaturalRow
{
    display: none;
}
</style>

<h1>Správa třídy</h1>
<table id="static_info">
    <tr>
        <td class='table_left'>ID třídy</td>
        <td class='table_right' id="id"><?= $classId ?></td>
        <td class='table_action'></td>
    </tr>
    <tr>
        <td class='table_left'>Název třídy</td>
        <td class='table_right' id="name"><?= $className ?></td>
        <td class='table_action'>
            <button id="changeNameButton" class="button" onclick="requestNameChange()">Vyžádat změnu</button>
            <div id="changeNameInput" style="display:none;">
                <input class="text" id="changeNameInputField" type=text placeholder="Nový název" maxlength=31 />
                <button class="button" id="changeNameConfirm" onclick="confirmNameChange()">Potvrdit</button>
                <button class="button" id="changeNameCancel" onclick="cancelNameChange()">Zrušit</button>
            </div>
        </td>
    </tr>
    <tr>
        <td class='table_left'>Stav třídy</td>
        <td class='table_right' id="status">
            <select id="statusInput" onchange="statusChange()" class="text dropList">
				<option value='Veřejná' <?php if ($classStatus === ClassObject::CLASS_STATUS_PUBLIC) : ?>selected<?php endif ?> title='Do veřejných tříd mají přístup všichni přihlášení uživatelé.'>Veřejná</option>
                <option value='Soukromá' <?php if ($classStatus === ClassObject::CLASS_STATUS_PRIVATE) : ?>selected<?php endif ?> title='Do soukromých tříd mohou vstoupit pouze uživatelé, kteří alespoň jednou zadali platný vstupní kód.'>Soukromá</option>
                <option value='Uzamčená' <?php if ($classStatus === ClassObject::CLASS_STATUS_LOCKED) : ?>selected<?php endif ?> title='Do uzamčených tříd nemohou vstoupit žádní uživatelé, kteří nedostali pozvánku.'>Uzamčená</option>
            </select>
        </td>
        <td class='table_action'>
        	<div id='statusCodeInput'>
        		<span>Vstupní kód:</span>
            	<input id='statusCodeInputField' type=number min=0 max=9999 maxlength=4 value="<?= $classCode ?>" style='width: 3.2rem;' class="text" oninput="statusChange()"/>
            </div>
            <button id="statusSaveButton" class="button" onclick="confirmStatusChange()">Aktualizovat</button>
            <button id="statusCancelButton" class="button" onclick="cancelStatusChange()">Zrušit</button>
        </td>
    </tr>
    <tr>
        <td class='table_left'>Členové třídy</td>
        <td id='membersCell' class='table_right' colspan=2>
        	<div id='membersUnavailable' <?php if ($classStatus !== ClassObject::CLASS_STATUS_PUBLIC) : ?>style="display:none;"<?php endif ?>>
        		Správa členů není dostupná pro veřejné třídy, jelikož všichni uživatelé služby mají do takové třídy přístup.
        	</div>
        	<div id='membersManagement'>
            	<table id='membersTable' <?php if ($classStatus === ClassObject::CLASS_STATUS_PUBLIC) : ?>style="display:none;"<?php endif ?>>
            	<?php foreach ($members as $member) : ?>
            	<tr class='membersTableRow'>
                    <td class='membersTableCell'><?= $member['name'] ?></td>
                    <td class='membersTableCell'>
                    	<button class='actionButton' onclick='kickUser(<?= $member['id'] ?>,"<?= $member['name'] ?>")' title='Odstranit ze třídy'><img src='images/cross.svg'/></button>
                    </td>
                </tr>
                <?php endforeach ?>
            	</table>
            
                <button id='inviteButton' class='actionButton' onclick='inviteFormShow()' title='Pozvat nového člena'><img src='images/plus.svg'></button>
                <div id='inviteForm' style="display:none;">
                    <div id='inviteUserInfo'>Pozvaný uživatel bude mít týden na přijmutí pozvánky. Pozvání nelze odvolat.</div>
                    <input id='inviteUserInput' placeholder='Jméno uživatele' type='text' maxlength=15>
                    <button onclick='inviteUser()' class='button'>Pozvat</button>
                    <button onclick='inviteFormHide()' class='button'>Zrušit</button>
                </div>
            </div>
        </td>
    </tr>
    <tr>
    	<td class='table_left'>Poznávačky</td>
    	<td id='testsCell' class='table_right' colspan=2>
    		<table id='testsTable'>
                <tr>
                    <th>Název</th>
                    <th>Části</th>
                    <th>Akce</th>
                </tr>
                <?php foreach ($groups as $group) : ?>
                <tr class='testsTableRow'>
                    <td class='testsTableCell'><?= $group->getName() ?></td>
                    <td class='testsTableCell'><?= $group->getPartsCount() ?></td>
                    <td class='testsTableCell'>
                        <button class='actionButton' onclick='manageTest(<?= $group->getId() ?>)' title='Spravovat hlášení'><img src='images/management.svg'></button>
                        <button class='actionButton' onclick='editTest(<?= $group->getId() ?>)' title='Upravit poznávačku'><img src='images/pencil.svg'></button>
                        <button class='actionButton' onclick='deleteTest(<?= $group->getId() ?>)' title='Odstranit poznávačku'><img src='images/cross.svg'/></button>
                    </td>
                </tr>
                <?php endforeach ?>
            </table>
            <button id='createButton' class='actionButton' onclick='createTest()' title='Vytvořit novou poznávačku'><img src='images/plus.svg'></button>
            <div id='createForm' style="display:none;">
                <div id='createInfo'>Zadejte název nové poznávačky. Do poznávačky budete moci přidat části a přírodniny později.</div>
                <input id='createInput' placeholder='Název poznávačky' type='text' class='text' maxlength=31>
                <button onclick='createTestSubmit()' class='button'>Vytvořit</button>
                <button onclick='createTestHide()' class='button'>Zrušit</button>
            </div>
    	</td>
    </tr>
</table>
    
<button class="button" id="deleteClassButton" onclick="deleteClass()">Zrušit třídu</button>
<div id="deleteClassInput1">
	<input class="text" id="deleteClassInputField" type=password placeholder="Zadejte své heslo" maxlength=31 />
	<button class="button" id="deleteClassConfirm" onclick="deleteClassVerify()">OK</button>
</div>
<div id="deleteClassInput2">
	<span>Tato akce je nevratná. Opravdu si přejete trvale odstranit tuto třídu, včetně všech poznávaček, přířodnin a obrázků, které do ní patří?</span><br>
	<button class="button" id="deleteClassFinalConfirm" onclick="deleteClassFinal()">Ano, zrušit třídu</button>
	<button class="button" id="deleteClassFinalCancel" onclick="deleteClassCancel()">Ne, zachovat třídu</button>
</div>

<a href="list.php"><button class="button">Zpět</button></a>