<h1>Členové třídy</h1>
<div id='membersManagement'>
	<table id='membersTable'>
    	<?php foreach ($members as $member) : ?>
    	<tr class='membersTableRow'>
            <td class='membersTableCell'><?= $member['name'] ?></td>
            <td class='membersTableCell'>
            	<button class='actionButton' onclick='kickUser(<?= $member['id'] ?>,"<?= $member['name'] ?>")' title='Odstranit ze třídy'><img src='images/cross.svg'/></button>
            </td>
        </tr>
        <?php endforeach ?>
	</table>
	
    <button id='inviteButton' class='actionButton' onclick='inviteFormShow()' title='Pozvat nového člena'><img src='images/plus.svg'></button>
    <div id='inviteForm' style="display:none;">
        <div id='inviteUserInfo'>Pozvaný uživatel bude mít týden na přijmutí pozvánky. Pozvání nelze odvolat.</div>
        <input id='inviteUserInput' placeholder='Jméno uživatele' type='text' maxlength=15>
        <button onclick='inviteUser()' class='button'>Pozvat</button>
        <button onclick='inviteFormHide()' class='button'>Zrušit</button>
    </div>
</div>