<div id='members-wrapper'>
    <section class="info-section">
        <h3>Správa členů třídy</h3>
        <p>Na této stránce můžeš spravovat členy tvé třídy.</p>
        <p>Pokud je tvá třída není nastavena jako veřejná, pouze tito uživatelé mohou tvou třídu používat.</p>
        <p>Pokud je tvá třída nastavena jako veřejná, mohou pouze tito uživatelé přidávat do poznávaček obrázky, za
        předpokladu, že jsi tuto funkci pro ostatní uživatele vypnul při nastavování třídy jako veřejné.</p>
        <p>Uživatel se může stát členem této třídy zadáním vstupního kódu (pokud jsi jej nastavil), nebo na základě
        přijetí pozvánky, kterou můžeš z této stránky odeslat.</p>
        <p>Pokud tuto třídu někdy v budoucnu nastavíš jako soukromou nebo uzamčenou, všichni uživatelé, kteří nejsou
        na tomto seznamu, k ní ztratí přístup.</p>
    </section>
    <section class="members-data-section">
        <?php foreach ($members as $member) : ?>
        <div class="member-data-item" data-member-id="<?= $member["id"] ?>">
            <span class='member-name'><?= $member['name'] ?></span>
            <div class="member-action">
                <?php if ($member->getId() !== \Poznavacky\Models\Statics\UserManager::getId()) : ?><button class='btn inline black kick-user-button'>Odebrat uživatele</button><?php endif ?>
            </div>
            <div class="kick-user" style="display: none">
                <span>Opravdu chceš odebrat tohoto uživatele ze třídy?</span>
                <div class="buttons">
                    <button class='btn border-btn non-transparent black kick-user-confirm-button'>Ano</button>
                    <button class='btn border-btn transparent black kick-user-cancel-button'>Zrušit</button>
                </div>
            </div>
        </div>
        <?php endforeach ?>
    </section>
    <section class="invite-user-section">
        <button id='invite-user-button' class="btn border-btn non-transparent black">Pozvat nového člena</button>
        <div id='invite-user-form' style="display: none;">
            <h3>Pozvat nového uživatele</h3>
            <p>Pozvaný uživatel bude mít týden na přijmutí pozvánky. Pozvání nelze odvolat.</p>
            <label for="invite-user-name">Jméno uživatele</label>
            <input id='invite-user-name' class="text-field" type='text' maxlength=15>
            <button class='btn border-btn non-transparent black' id="invite-user-confirm-button">Pozvat</button>
            <button class='btn inline black' id="invite-user-cancel-button">Zrušit</button>
        </div>
    </section>
</div>