<div id="menu-classes-table" class="folders">
	<div class="table-title rows">
		<span class="col1">Název třídy</span>
		<span class="col2">Poznávačky</span>
		<span class="col3">Akce</span>
	</div>
	<ul class="rows">
		<?php foreach ($table as $tableRow) : ?>
			<button class="btn" onclick="window.location.href='<?= $tableRow['rowLink'] ?>'"><li>
				<h4 class="col1">
					<!--<a href="<?= $tableRow['rowLink'] ?>">
					<?= $tableRow[0] ?>
					</a>-->
					<?= $tableRow[0] ?>
				</h4>
				<span class="col2">
					<span class="tiles">poznávaček: </span>
					<!--<a href="<?= $tableRow['rowLink'] ?>">
					<?= $tableRow[1] ?>
					</a>-->
					<span><?= $tableRow[1] ?></span>
				</span>
				<?php if ($tableRow[2] === 'admin') : ?>
				<a href="<?= $tableRow['rowLink'].'/'.'manage' ?>" class="btn inline black col3">Správa třídy</a>
				<?php endif ?>
				<?php if ($tableRow[2] === 'leave') : ?>
				<a href="<?= $tableRow['rowLink'].'/'.'leave' ?>" class="btn inline black col3">Opustit třídu</a>
				<?php endif ?>
				<?php if ($tableRow[2] !== 'admin' && $tableRow[2] !== 'leave' ) : ?>
				<?= $tableRow[2] ?>
				<?php endif ?>
			</li></button>
			
		<?php endforeach; ?>
		<li id="enter-code-wrapper">
			<h5>Připojte se pomocí kódu</h5>
			<span>Zadejte kód soukromé třídy, do které chcete vstoupit:</span>
			<form id='class-code-form' action="menu/enter-class-code" method="POST">
				<input id='class-code-input' class="text-field" type="number" name="code" min=0 max=9999 maxlength=4 required/>
				<input class='btn border-btn non-transparent black' type="submit" value="OK">
			</form>
		</li>
		<li id="request-class-wrapper">
			<h5>Vytvořte novou třídu</h5>
			<span>Vyplňte krátký formulář pro tvorbu třídy:</span>
			<a id="request-new-class-button" href="menu/request-new-class" class='btn border-btn non-transparent black'>Zažádat o vytvoření nové třídy</a> <!-- TEMPORARY -->
		</li>
	</ul>
</div>