<header>
	<h1>Poznávačky</h1>
	<div class="login-info">
		<span>Přihlášen: <?= $loggedUserName ?></span>
		<button>Odhlásit se</button>
	</div>
</header>
<aside class="aside-left">
	<nav>
		<a>Nastavení účtu</a>
		<?php require 'Views/navigation.phtml';?> <!-- RYCHLÁ NAVIGACE -->
	</nav>
</aside>
<main>
	<?php $this->controllerToCall->displayView(); ?> <!-- HLAVNÍ OBSAH STRÁNKY -->
</main>
<aside class="aside-right">
</aside>