<?= $this->controllerToCall->displayView() ?>

<div id="menu-classes-forms">
	<button id="enter-class-code-btn" class='btn border-btn non-transparent rounded black' onclick='enterClassCode()'>Zadat kód soukromé třídy</button>
	<form id='class-code-form' action="menu/enter-class-code" method="POST" style="display: none"><!-- Po zprovoznění JavaScriptu přidat formuláři vlastnost style="display:none;" -->
		<input id='class-code-input' class="text-field" type="number" name="code" min=0 max=9999 maxlength=4 required/>
		<input class='btn border-btn non-transparent rounded black' type="submit" value="OK">
		<button class='btn border-btn transparent rounded black' onclick='closeClassCode()'>Zpět</button>
	</form>
	<a href="menu/request-new-class" class='btn border-btn non-transparent rounded black'>Zažádat o vytvoření nové třídy</a>
</div>
