<div id="menu-classes-table" class="folders">
    <?php if (!empty($table)) : ?>
    <div class="table-title rows">
        <span class="class name">Název třídy</span>
        <span class="class tests-count">Poznávačky</span>
        <span class="class action">Akce</span>
    </div>
    <?php endif ?>
    <ul class="rows">
        <?php foreach ($table as $tableRow) : ?>
            <button class="btn class data-item" data-class-url="<?= $tableRow['rowLink'] ?>" ><li>
                <h4 class="class name">
                    <?= $tableRow[0] ?>
                </h4>
                <span class="class tests-count">
                    <span><?= $tableRow[1] ?></span>
                </span>
                <?php if (!$demoVersion): ?>
                    <?php if ($tableRow[2] === 'admin') : ?>
                    <a href="<?= $tableRow['rowLink'].'/'.'manage' ?>" title="Nastavení třídy" class="btn icon class action"><img class="icon black" src="images/settings_f.svg"></a>
                    <?php endif ?>
                    <?php if ($tableRow[2] === 'leave') : ?>
                    <a data-leave-url="<?= $tableRow['rowLink'].'/'.'leave' ?>" title="Opustit třídu" class="btn icon class action leave-link"><img class="icon black" src="images/logout_f.svg"></a>
                    <?php endif ?>
                    <?php if ($tableRow[2] !== 'admin' && $tableRow[2] !== 'leave' ) : ?>
                    <?= $tableRow[2] ?>
                    <?php endif ?>
                <?php endif ?>
            </li></button>
        <?php endforeach ?>

        <?php foreach ($invitations as $invitation) : ?>
        <li class="invitation-wrapper" data-class-url="<?= $invitation->getClass()->getUrl() ?>">
            <span class="invitation info">Pozvánka do třídy (vyprší <?= $invitation->getExpirationDate(); ?>)</span>
            <h4 class="class name"><?= $invitation->getClass()->getName(); ?></h4>
            <span class="class tests-count"><?= $invitation->getClass()->getGroupsCount() ?></span>
            <div class="invitation action">
                <button class="btn icon accept-invitation-button" title="Přijmout pozvánku"><img class="icon green" src='images/tick-thick.svg' alt="Přijmout pozvánku"></button>
                <button class="btn icon reject-invitation-button" title="Odmítnout pozvánku"><img class="icon black" src='images/cross-thick.svg' alt="Odmítnout pozvánku"></button>
            </div>
        </li>
        <?php endforeach ?>

        <?php if (!$demoVersion): ?>
        <li id="enter-code-wrapper">
            <h5>Připoj se pomocí kódu</h5>
            <span>Zadej kód soukromé třídy, do které chceš vstoupit:</span>
            <form id='class-code-form'>
                <input id='class-code-input' class="text-field" type="number" min=0 max=9999 maxlength=4/>
                <button class='btn border-btn non-transparent primary'>OK</button>
            </form>
        </li>
        <li id="request-class-wrapper">
            <h5>Vytvoř novou třídu</h5>
            <span>Ve své třídě můžeš vytvářet jednotlivé poznávačky a sdílet je se spolužáky. Pro tvorbu třídy vyplň krátký formulář:</span>
            <button id="request-class-button" class='btn border-btn non-transparent primary'>Vytvořit novou třídu</button> <!-- TEMPORARY -->
            <form method="POST" id="request-class-form" style="display:none;">
                <label for="new-class-form-name">Požadovaný název třídy
                    <p class="additional-form-info">Pokus se do názvu třídy zakomponovat i název školy, aby nedocházelo ke konfliktům v názvech mezi třídami různých škol. Vhodným názvem třídy je například <i>2.A ZŠ Jana Nerudy</i> nebo <i>Biologický kroužek GJVJ</i>.</p>
                    <p class="additional-form-info">Třída bude vytvořena ihned po odeslání žádosti s dočasným názvem <i>Třída uživatele <?= $userName ?></i>. Požadovaný název třídy bude automaticky nastaven, pokud ho schválí správce služby.</p>
                </label>
                <input id='new-class-form-name' class="text-field" type=text maxlength=31 />
                <?php if (!$specifiedEmail) : ?>
                    <label for="new-class-form-email">Kontaktní e-mailová adresa</label>
                    <input class='text-field' id='new-class-form-email' length=255 />
                <?php endif ?>
                <label for="new-class-form-antispam">Prokaž prosím, že nejsi robot, opsáním následujícího čísla pomocí číslic: <span id="antispam-question"> <?= $antispamCode ?> </span></label>
                <input id='new-class-form-antispam' class="text-field" type="number" min=0 max=99 maxlength=2 />
                <input type=submit class="btn border-btn non-transparent primary" value="Odeslat žádost" />
                <button id="request-class-cancel-button" class="btn inline black">Zrušit</button>
            </form>
        </li>
        <?php endif ?>
    </ul>
    <?php if ($demoVersion): ?>
    <div id="demo-info" class="center">
        <p>Pokud si založíš účet, můžeš si vytvořit vlastní třídy s vlastními poznávačkami!</p>
    </div>
    <?php endif ?>
</div>

<div id="class-template" class="data-item-template" style="display: none;">
    <button class="btn class data-item" data-class-url="/menu/{url}"><li>
        <h4 class="class name">{name}</h4>
        <span class="class test-count">{groups}</span>
        <a data-leave-url="/menu/{url}/leave" title="Opustit třídu" class="btn icon class action leave-link"><img class="icon black" src="images/logout_f.svg"></a>
    </li></button>
</div>
