<section class="info-section" style="display: none">
    <h3>Nápověda</h3>
    <p>Na této stránce si můžeš zvolit, jak se chceš učit.</p>
    <ul class="list">
        <li>V seznamu vidíš všechny části, na které je zvolená poznávačka rozdělena.</li>
        <li>Po rozkliknutí konkrétní části si můžeš vybrat mezi třemi možnostmi: <i>Přidat obrázky</i>, kde můžeš k přírodninám přidávat fotky, <i>Učit se</i>, kde si můžeš fotky procházet, a <i>Vyzkoušet se</i>, kde se ti budou generovat náhodné obrázky a tvým úkolem bude je pojmenovat.</li>
        <li>Funkci <i>Přidat obrázky</i> může správce třídy omezit, v takovém případě ti nebude dostupná.</li>
        <li>Funkce <i>Učit se</i> a <i>Vyzkoušet se</i> nejsou dostupné, pokud v poznávačce zatím nejsou přidané žádné obrázky.</li>
    </ul>
</section>
<div id="menu-parts-table" class="folders">
    <div class="table-title rows">
        <span class="part name">Název části</span>
        <span class="part naturals-count">Přírodniny</span>
        <span class="part pictures-count">Obrázky</span>
    </div>
    <ul class="rows">
    <?php foreach ($table as $tableRow) : ?>
        <button class="btn data-item display-buttons-button <?php if ($tableRow[1] == '0') : ?>disabled<?php endif ?>"><li <?php if ($tableRow[1] == '0') : ?>class="empty"<?php endif ?>>
            <h4 class="part name"><?= $tableRow[0] ?></h4>
                <span class="part naturals-count"> <?= $tableRow[1] ?> </span>
                <span class="part pictures-count"> <?= $tableRow[2] ?> </span>
            <?php if ($tableRow[1] > 0) : ?>
            <div class="buttons-wrapper">
                <div class="buttons">
                    <a href="<?= $tableRow['rowLink'].'/add-pictures' ?>" class="btn transparent primary border-btn<?php if ($demoVersion || !$displayAddPicturesButton) : ?> disabled<?php endif ?>">Přidat obrázky</a>
                    <a href="<?= $tableRow['rowLink'].'/learn' ?>" class="btn transparent primary border-btn<?php if ($tableRow[2] === 0) : ?> disabled<?php endif ?>">Učit se</a>
                    <a href="<?= $tableRow['rowLink'].'/test' ?>" class="btn transparent primary border-btn<?php if ($tableRow[2] === 0) : ?> disabled<?php endif ?>">Vyzkoušet se</a>
                </div>
            </div>
            <?php endif ?>
            <?php if ($tableRow[1] === '0') : ?>
                <div class="info">Pro používání této části do ní musí být nejprve přidány přírodniny</div>
            <?php endif ?>
        </li></button>
    <?php endforeach; ?>
    </ul>
</div>
