<table>
	<tr>
		<th>Název třídy</th>
		<th>Poznávačky</th>
		<th>Akce</th>
	</tr>
	<?php foreach ($tableData as $tableRow) : ?>
		<tr>
    		<?php for ($i = 0; $i < 3; $i++) : ?>
    		<td>
    			<a href="<?= $currentAddress ?>/<?= $tableRow[0] ?>"><!-- na nultém indexu je název třídy -->
    			<?= $tableRow[$i] ?>
				</a>
    		</td>
    		<?php endfor; ?>
    	</tr>
	<?php endforeach; ?>
</table>