<header>
	<button class="btn hamburger-btn" onclick="showPanel()"><img src="../images/hamburger.svg"></button>
	<div class="logo">
		<img src=""> <!-- LOGO -->
		<h1>Poznávačky</h1>
	</div>
</header>
<aside>
	<nav id="aside-main-panel">
		<button class="btn" onclick="showAdditionalPanel('aside-login-info')"><img src="../images/user.svg" alt=""></button> <!--zobrazí info o uživateli-->
		<button class="btn" onclick="showAdditionalPanel('aside-nav')"><img src="../images/navigation.svg" alt=""></button> <!--zobrazí navigaci-->
		<button class="btn" onclick="showAdditionalPanel('aside-settings')"><img src="../images/settings.svg" alt=""></button> <!--zobrazí nastavení-->
	</nav>
	<div id="aside-additional-panel">
		<div id="aside-login-info">
			<span>Přihlášen: <?= $loggedUserName ?></span>
			<a href="menu/account-settings" class="btn inline black">Nastavení účtu</a>
			<a href='logout' class="btn inline black">Odhlásit se</a>
			<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam eius fugiat error! Debitis itaque excepturi ratione eaque labore? Explicabo commodi maxime excepturi in praesentium porro quia quisquam provident, voluptatem molestias numquam modi aut consequatur fugiat veritatis aspernatur aliquid quibusdam totam sint quidem atque. Distinctio autem minima ducimus fugit ullam totam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam aspernatur hic perferendis ipsa voluptas cum quo amet modi ex natus odit, dignissimos sit nam consequuntur numquam. Atque incidunt quos alias corrupti asperiores quia placeat nisi esse adipisci nam numquam explicabo recusandae repudiandae expedita ipsam, officiis autem! Iusto sunt sint saepe?</p>
		</div>
		<nav id="aside-nav">
			<?php if ($adminLogged) : ?>
				<a href="administrate">Správa systému</a>
			<?php endif ?>
			<a href="menu/account-settings">Nastavení účtu</a>
			<?php require 'Views/navigation.phtml';?> <!-- RYCHLÁ NAVIGACE -->
		</nav>
		<div id="aside-settings">
			<button class="btn rounded transparent white border-btn" onclick="changeMenuView()">Přepnout zobrazení menu</button>
		</div>
		<button class="btn cross" onclick="closePanel()"><img src="../images/crossButtonWhite.svg" alt=""></button>
	</div>
</aside>
<main class="menu">
	<?php $this->controllerToCall->displayView(); ?> <!-- HLAVNÍ OBSAH STRÁNKY -->
</main>