<?= $this->controllerToCall->displayView() ?>
<button class='button' onclick='newClass()'>Zažádat o vytvoření nové třídy</button>
<div id='classCodeBtn' style='display:block;'>
    <button class='button' onclick='enterClassCode()'>Zadat kód soukromé třídy</button>
</div>
<div id='classCodeForm' style='display:none;'>
    <input id='classCodeInput' type=text maxlength=4 style='width: 2rem;'/>
    <button class='button' onclick='submitClassCode()'>OK</button>
    <button class='button' onclick='closeClassCode()'>Zpět</button>
</div>