<div id="menu-groups-table" class="folders">
	<div class="table-title rows">
		<span class="col1">Název poznávačky</span>
		<span class="col2">Části</span>
	</div>
	<ul class="tiles">
	<?php foreach ($table as $tableRow) : ?>
		<button class="btn" onclick="window.location.href='<?= $tableRow['rowLink'] ?>'"><li>
    		
    		<h4 class="col1">
    			<!--<a href="<?= $tableRow['rowLink'] ?>">-->
    			<?= $tableRow[0] ?>
				<!--</a>-->
    		</h4>
			<span class="col2">
				<span>částí: </span>
				<span><?= $tableRow[1] ?></span>
			</span>	
		</li></button>
	<?php endforeach ?>
	</ul>
</div>