<header>
	<a class="btn icon" href="menu/account-settings"><img src="../images/user.svg" alt=""></a> 
	<a class="btn icon" href="administrate"><img src="../images/settings.svg" alt=""></a> 
	<div class="logo">
		<img src=""> <!-- LOGO -->
		<h1>Poznávačky</h1>
	</div>
	<a class="btn icon" href='logout'><img src="../images/logout.svg" alt=""></a>
</header>
<aside>
	<?php if (!$demoVersion) : ?><a class="btn icon" href="menu/account-settings"><img src="../images/user.svg" alt=""></a><?php endif ?>
	<?php if ($adminLogged) : ?><a class="btn icon" href="administrate"><img src="../images/settings.svg" alt=""></a><?php endif ?>
	<a class="btn icon" href='logout'><img src="../images/logout.svg" alt=""></a>
</aside>
<main class="menu">
	<h2 id="level-nav">
		<nav>
		<?php for ($i = 0; $i < count($navigationBar); $i++) : ?>
			<?php if ($i < count($navigationBar) - 1) : ?>
				<a class="btn inline black" href="<?= $navigationBar[$i]['link'] ?>"><?= $navigationBar[$i]['text'] ?></a>
				<span>>></span>
			<?php endif ?>
			<?php if ($i == count($navigationBar) - 1) : ?>
				<span><?= $navigationBar[$i]['text'] ?></span>
			<?php endif ?>
		<?php endfor ?>
		</nav>
	</h2>
	<div class="wrapper">
		<?php $this->controllerToCall->displayView(); ?> <!-- HLAVNÍ OBSAH STRÁNKY -->
	</div>
</main>