<header>
	<h1>Poznávačky</h1>
	<div class="login-info">
		<span>Přihlášen: <?= ?> <!-- KDO JE PŘIHLÁŠEN --></span>
		<button>Odhlásit se</button>
	</div>
</header>
<aside class="aside-left">
	<nav>
		<a>Nastavení účtu</a>
		<?= ?> <!-- RYCHLÁ NAVIGACE -->
	</nav>
</aside>
<main>
	<?php $this->controllerToCall->displayView(); ?> <!-- HLAVNÍ OBSAH STRÁNKY -->
</main>
<aside class="aside-right">
</aside>
<footer>
	<a id="help" class="footer-option" target='_blank' href="https://github.com/HonzaSTECH/Poznavacky/wiki">Nápověda</a>
	<a id="issues" class="footer-option" onclick="showLogin()" target='_blank' href="https://github.com/HonzaSTECH/Poznavacky/issues/new/choose">Nalezli jste problém?</a>
	<a id="terms" class="footer-option" target='_blank' href='https://github.com/HonzaSTECH/Poznavacky/blob/master/documents/TERMS_OF_SERVICE.md'>Podmínky služby</a>
	<span id="about" class="footer-option">&copy Štěchy a Eksyska, 2019</span>
    <!--<script>
        function showLogin()
        {
            alert("Přihlašovací údaje pro nahlašování chyby:\nJméno: gjvj\nHeslo: poznavacky71");
        }
    </script>--> <!-- BUDE PŘEDĚLÁNO -->
</footer>