<table>
    <tr>
        <th>Současné jméno</th>
        <th>Požadované jméno</th>
        <th>Akce</th>
    </tr>
    <?php if (count($userNameChangeRequests) + count($classNameChangeRequests) === 0) : ?>
    <tr><td colspan=3>Žádné žádosti k vyřízení</td></tr>
    <?php endif ?>
    <?php if (count($userNameChangeRequests) > 0) : ?>
    <tr><td colspan=3>Požadavky na změnu uživatelského jména</td></tr>
    <?php endif ?>
    <?php foreach ($userNameChangeRequests as $request) : ?>
    <tr>
    	<td><?= $request->getOldName(); ?></td>
    	<td><?= $request->getNewName(); ?></td>
    	<td>
    		<button class='name-change-action active-btn' onclick='acceptNameChange(event, "user", <?= $request->getId() ?>)' title='Přijmout'>
    			<img src='images/tick.svg'/>
    		</button>
    		<button class='name-change-action active-btn' onclick='declineNameChange(event, "user", <?= $request->getId() ?>)' title='Zamítnout'>
    			<img src='images/cross.svg'/>
    		</button>
    		<?php if (empty($request->getRequestersEmail())) : ?>
			<button class='name-change-action grayscale' disabled>
    		<?php endif ?>
    		<?php if (!empty($request->getRequestersEmail())) : ?>
			<button class='name-change-action active-btn' onclick='startMail("<?= $request->getRequestersEmail() ?>")' title='Poslat e-mail'>
    		<?php endif ?>
    			<img src='images/mail.svg'/>
    		</button>
    	</td>
    </tr>
    <?php endforeach ?>
    
    <?php if (count($classNameChangeRequests) > 0) : ?>
    <tr><td colspan=3>Požadavky na změnu jména třídy</td></tr>
    <?php endif ?>
    <?php foreach ($classNameChangeRequests as $request) : ?>
    <tr>
    	<td><?= $request->getOldName(); ?></td>
    	<td><?= $request->getNewName(); ?></td>
    	<td>
    		<button class='name-change-action active-btn' onclick='acceptNameChange(event, "class", <?= $request->getId() ?>)' title='Přijmout'>
    			<img src='images/tick.svg'/>
    		</button>
    		<button class='name-change-action active-btn' onclick='declineNameChange(event, "class", <?= $request->getId() ?>)' title='Zamítnout'>
    			<img src='images/cross.svg'/>
    		</button>
    		<?php if (empty($request->getRequestersEmail())) : ?>
			<button class='name-change-action grayscale' disabled>
    		<?php endif ?>
    		<?php if (!empty($request->getRequestersEmail())) : ?>
			<button class='name-change-action active-btn' onclick='startMail("<?= $request->getRequestersEmail() ?>")' title='Poslat e-mail'>
    		<?php endif ?>
    			<img src='images/mail.svg'/>
    		</button>
    	</td>
    </tr>
    <?php endforeach ?>
</table>