<table>
    <tr>
        <th>Typ</th>
        <th>Současné jméno</th>
        <th>Požadované jméno</th>
        <th>Akce</th>
    </tr>
    <?php if (count($userNameChangeRequests) + count($classNameChangeRequests) === 0) : ?>
    <tr><td colspan=4>Žádné žádosti k vyřízení</td></tr>
    <?php endif ?>
    <?php foreach ($userNameChangeRequests as $request) : ?>
    <tr class="name-change-request data-item"
        data-request-id="<?= $request->getId() ?>"
        data-request-email="<?= $request->getRequestersEmail() ?>"
        data-object-type="user">
        <td>
            Uživatel
        </td>
        <td>
            <?= $request->getOldName(); ?>
        </td>
        <td>
            <?= $request->getNewName(); ?>
        </td>
        <td class="name-change-request action">
            <div>
                <button class='btn icon accept-name-change-button' title='Přijmout'>
                    <img class="icon green" src='images/tick-thick.svg'/>
                </button>
                <button class='btn icon decline-name-change-button' title='Zamítnout'>
                    <img class="icon black" src='images/cross-thick.svg'/>
                </button>
                <button class='btn icon start-mail-button <?php if (empty($request->getRequestersEmail())) : ?>disabled<?php endif ?>' title='Poslat e-mail uživateli'>
                    <img class="icon" src='images/mail_f_colour.svg'/>
                </button>
            </div>
        </td>
    </tr>
    <?php endforeach ?>
    <?php foreach ($classNameChangeRequests as $request) : ?>
    <tr class="name-change-request data-item"
        data-request-id="<?= $request->getId() ?>"
        data-request-email="<?= $request->getRequestersEmail() ?>"
        data-object-type="class">
        <td>
            Třída
        </td>
        <td>
            <?= $request->getOldName(); ?>
        </td>
        <td>
            <?= $request->getNewName(); ?>
        </td>
        <td class="name-change-request action">
            <div>
                <button class='btn icon accept-name-change-button' title='Přijmout'>
                    <img class="icon green" src='images/tick-thick.svg'/>
                </button>
                <button class='btn icon decline-name-change-button' title='Zamítnout'>
                    <img class="icon black" src='images/cross-thick.svg'/>
                </button>
                <button class='btn icon start-mail-button <?php if (empty($request->getRequestersEmail())) : ?>disabled<?php endif ?>' title='Poslat e-mail správci'>
                    <img class="icon" src='images/mail_f_colour.svg'/>
                </button>
            </div> 
        </td>
    </tr>
    <?php endforeach ?>
</table>