<section class="info-section" style="display: none">
    <h3>Nápověda</h3>
    <p>Na této stránce můžeš spravovat přírodniny, které ve tvé třídě existují.</p>
    <ul class="list">
        <li>Nahrané obrázky jsou pevně svázány s jednotlivými přírodninami. Odstraněním přírodniny dojde i k odstranění všech obrázků, které k ní byly přidány.</li>
        <li>Odstraněním přírodniny, která je přiřazená do alespoň jedné poznávačky, ji odebereš i ze všech poznávaček a jejich částí.</li>
        <li>Přejmenováním přírodniny dojde k aktualizaci názvu ve všech poznávačkách, ve kterých se přírodnina vyskytuje.</li>
        <li>Nové přírodniny jsou přidávány automaticky při tvorbě nebo úpravě poznávaček. Přírodniny jsou automaticky seřazeny podle data přidání.</li>
        <li>Parametr, podle něhož jsou přírodniny řazeny, můžeš změnit. Také můžeš filtrovat přírodniny podle názvu (konkrétně písmen, kterými název přírodniny začíná).</li>
    </ul>
</section>
<div id='naturals-wrapper'>
    <section class="naturals-filter-section">
        <div id="filter-search">
            <label for="filter-name">Vyhledat přírodninu: </label>
            <input type="text" id="filter-name" class="text-field">
        </div>
        <button id="remove-filters-button" class="btn icon" title="Zrušit všechny filtry">
            <img src="images/clear-filter-black.svg" alt="">
        </button>
    </section>
    <section id="naturals-data-section">
        <div class="naturals-data-properties">
            <div>
                <span class="natural-name">Název přírodniny</span>
                <div class="sort-buttons">
                    <button class="btn icon sort-up-button" title="Seřadit vzestupně">
                        <img src="images/triangle-up-black.svg" alt="">
                    </button>
                    <button class="btn icon sort-down-button" title="Seřadit sestupně">
                        <img src="images/triangle-down-black.svg" alt="">
                    </button>
                </div>
            </div>
            <div>
                <span class="natural-uses-count">Počet výskytů</span>
                <div class="sort-buttons">
                    <button class="btn icon sort-up-button" title="Seřadit vzestupně">
                        <img src="images/triangle-up-black.svg" alt="">
                    </button>
                    <button class="btn icon sort-down-button" title="Seřadit sestupně">
                        <img src="images/triangle-down-black.svg" alt="">
                    </button>
                </div>
            </div>
            <div>
                <span class="natural-pictures-count">Počet obrázků</span>
                <div class="sort-buttons">
                    <button class="btn icon sort-up-button" title="Seřadit vzestupně">
                        <img src="images/triangle-up-black.svg" alt="">
                    </button>
                    <button class="btn icon sort-down-button" title="Seřadit sestupně">
                        <img src="images/triangle-down-black.svg" alt="">
                    </button>
                </div>
            </div>
            <span class="natural-action">Akce</span>
        </div>
        <?php foreach ($naturals as $natural) : ?>
        <div class="natural-data-item" data-natural-id="<?= $natural->getId() ?>">
            <div class="natural-name-wrapper">
                <div class="natural-name-box">
                    <span class="natural-name"><?= $natural->getName() ?></span>
                </div>
                <div class="natural-name-input-box" style="display:none;">
                    <input type="text" maxlength="31" class="text-field natural-name-input" value="<?= $natural->getName() ?>"/>
                </div>
            </div>
            <span class="natural-uses-count"><?= $natural->getUsesCount() ?></span>
            <span class="natural-pictures-count"><?= $natural->getPicturesCount() ?></span>
            <div class="natural-action">
                <div class="normal-buttons">
                    <button title="Přejmenovat" class="rename-natural-button btn inline black">Přejmenovat</button>
                    <button title="Odebrat" class="remove-natural-button btn inline black">Odebrat</button>
                </div>
                <div class="rename-buttons" style="display:none;">
                    <button class="rename-confirm-button btn inline black">Potvrdit</button>
                    <button class="rename-cancel-button btn inline black">Zrušit</button>
                </div>
            </div>
        </div>
        <?php endforeach ?>
    </section>
</div>