<header>
	<div class="logo">
		<!-- <img src="">  LOGO -->
		<h1>Poznávačky</h1>
	</div>
</header>
<main>
	<div class="wrapper">
		<h2>Změna hesla uživatele <?= $username ?></h2>
		<form method="POST" action="token-password-change">
			<div class="user-data">
				<input type=hidden name="token" value="<?= $token ?>" />
				<label for="new-pass">Nové heslo</label>
				<div class="input-wrapper">
					<input id="new-pass" class="text-field" type=password maxlength=31 name="pass" required />
					<div class="checkmark"><img src="../images/check.svg"></div>
				</div>
				<div id="new-pass-message" class="message"></div>
				<label for="new-repass">Nové heslo znovu</label>
				<div class="input-wrapper">
					<input id="new-repass" class="text-field" type=password maxlength=31 name="repass" required />
					<div class="checkmark"><img src="../images/check.svg"></div>
				</div>
				<div id="new-repass-message" class="message"></div>
			</div>
			<button class="btn border-btn non-transparent black" type=submit>Změnit heslo</button>
			<div id="new-server-message" class="message server"></div>
		</form>
	</div>
</main>