<div id="logo-standalone">
    <img src="images/icon-white.svg" alt="Logo Poznávaček">
</div>
<header>
</header>
<main>
    <div class="content">
        <h2>Změna hesla uživatele <?= $username ?></h2>
        <form id="recover-password-form">
            <div class="user data">
                <input id="token" type=hidden value="<?= $token ?>" />
                <label for="new-pass">Nové heslo</label>
                <div class="input-wrapper">
                    <input id="new-pass" class="text-field" type=password maxlength=31 />
                    <div class="checkmark"><img class="icon green" src="images/check-thick.svg" alt="Zkontrolováno"></div>
                </div>
                <div id="new-pass-message" class="message"></div>
                <label for="new-repass">Nové heslo znovu</label>
                <div class="input-wrapper">
                    <input id="new-repass" class="text-field" type=password maxlength=31 />
                    <div class="checkmark"><img class="icon green" src="images/check-thick.svg" alt="Zkontrolováno"></div>
                </div>
                <div id="new-repass-message" class="message"></div>
            </div>
            <button id="change-password-button" class="btn border-btn non-transparent primary">Změnit heslo</button>
            <div id="new-server-message" class="message server"></div>
        </form>
    </div>
</main>

