<main id="pw_recovery">
	<span>Změnit heslo uživatele <?= $username ?></span>
	<form id="recover-password-form">
    	<input id="token-input" type=hidden value="<?= $token ?>" />
    	<input id="pass-input" class="text" type=password maxlength=31 placeholder="Nové heslo" required /><br>
    	<input id="repass-input" class="text" type=password maxlength=31 placeholder="Nové heslo znovu" required /><br>
    	<input id="submit-button" class="button" type=submit value="Změnit heslo" />
	</form>
</main>
