<select onchange="updateReport()">
	<option><?= Report::REASON_NOT_DISPLAYING ?></option>
	<option><?= Report::REASON_LONG_LOADING ?></option>
	<option><?= Report::REASON_INCORRECT_NATURAL ?></option>
	<option><?= Report::REASON_CONTAINS_NAME ?></option>
	<option><?= Report::REASON_BAD_RESOLUTION ?></option>
	<option><?= Report::REASON_COPYRIGHT ?></option>
	<option><?= Report::REASON_OTHER ?></option>
	<option><?= Report::REASON_OTHER_ADMIN ?></option>
</select>
<div>
	<!-- Zde se bude zobrazovat další vstupní pole při vybrání některých hlášení -->
</div>
<button onclick="submitReport(event)">Odeslat</button>
<button onclick="cancelReport(event)">Zrušit</button>