<style>
    /* Dočasné styly - až tohle budeš stylovat, přesuň si to kam budeš potřebovat */
    /* Styly zkopírovány z private.css */
    .activeBtn,
    .grayscale {
      height: 1.2rem;
      width: 1.2rem;
      padding: 0;
      margin: 0 0.2rem;
      vertical-align: middle;
    }
    
    .activeBtn img,
    .grayscale img {
      height: 1.2rem;
      width: 1.2rem;
    }
</style>
<?php require 'Views/reportsTableManage.phtml'; ?>
<?php require 'Views/reportedPicturePreview.phtml'; ?>
