<!--<select class="report-reason" onchange="updateReport()">
	<option><?= Report::REASON_NOT_DISPLAYING ?></option>
	<option><?= Report::REASON_LONG_LOADING ?></option>
	<option><?= Report::REASON_INCORRECT_NATURAL ?></option>
	<option><?= Report::REASON_CONTAINS_NAME ?></option>
	<option><?= Report::REASON_BAD_RESOLUTION ?></option>
	<option><?= Report::REASON_COPYRIGHT ?></option>
	<option><?= Report::REASON_OTHER ?></option>
	<option><?= Report::REASON_OTHER_ADMIN ?></option>
</select>-->
<div class="custom-select-wrapper" id="report-reason">
	<div class="custom-select">
		<div class="custom-select-main">
			<span><?= Report::REASON_NOT_DISPLAYING ?></span>
			<img class="arrow" src="../images/arrowBlack.svg">
		</div>
		<ul class="custom-options">
			<li class="custom-option"><?= Report::REASON_NOT_DISPLAYING ?></li>
			<li class="custom-option"><?= Report::REASON_LONG_LOADING ?></li>
			<li class="custom-option"><?= Report::REASON_INCORRECT_NATURAL ?></li>
			<li class="custom-option"><?= Report::REASON_CONTAINS_NAME ?></li>
			<li class="custom-option"><?= Report::REASON_BAD_RESOLUTION ?></li>
			<li class="custom-option"><?= Report::REASON_COPYRIGHT ?></li>
			<li class="custom-option"><?= Report::REASON_OTHER ?></li>
			<li class="custom-option"><?= Report::REASON_OTHER_ADMIN ?></li>
		</ul>
	</div>
</div>
<div class="additional-report-info">
	<div class="custom-select-wrapper" id="long-loading-info" style="display: none">
		<div class="custom-select">
			<div class="custom-select-main">
				<span><?= Report::LONG_LOADING_AVAILABLE_DELAYS[0] ?></span>
				<img class="arrow" src="../images/arrowBlack.svg">
			</div>
			<ul class="custom-options">
				<?php foreach (Report::LONG_LOADING_AVAILABLE_DELAYS as $delay) : ?>
					<li class="custom-option"><?= $delay ?></li>
				<?php endforeach ?>
			</ul>
		</div>
	</div>
	<input id="incorrect-natural-info" type='text' class='text' placeholder='Přírodnina na obrázku' maxlength=31 style="display:none;">
	<textarea id="other-info" class='text' placeholder='Specifikujte prosím důvod.&#10;Toto hlášení obdrží pouze správce této třídy.' maxlength=255 style="display:none;"></textarea>
	<textarea id="other-admin-info" class='text' placeholder='Specifikujte prosím důvod.&#10;Toto hlášení obdrží pouze správce celého systému.&#10;Používejte prosím tuto možnost pouze pro případy, při kterých je nutný zásah administrátora.' maxlength=255 style="display:none;"></textarea>
</div>
<button class="btn border-btn non-transparent black" onclick="submitReport(event)">Odeslat</button>
<button class="btn border-btn non-transparent black" onclick="cancelReport(event)">Zrušit</button>
