<div id="resolve-reports-wrapper">
    <div class="reports data-properties" <?php if (count($reports) === 0) : ?>style="display: none"<?php endif ?>>
        <span class="report-name">Přírodnina</span>
        <span class="report-url">Zdroj</span>
        <span class="report-reason">Důvod</span>
        <span class="report-additional-info">Další informace</span>
        <span class="report-number">Počet nahlášení</span>
        <span class="report-action">Akce</span>
    </div>
    <?php if (count($reports) === 0) : ?>
    <p>Žádná hlášení k vyřízení</p>
    <?php endif ?>
    <?php foreach ($reports as $report) : ?>
    <div class="report data-item"
            data-picture-id="<?= $report->getPictureId() ?>"
            data-report-id="<?= $report->getId() ?>"
            data-report-url="<?= $report->getUrl() ?>">
        <span class="report-name"><?= $report->getNaturalName() ?></span>
         <div class="report-name-edit" style="display: none">
            <div class="custom-select-wrapper report-natural-select">
                <div class="custom-select">
                    <div class="custom-select-main">
                        <span><?= $report->getNaturalName() ?></span>
                        <img class="arrow" src="images/arrow-black.svg" alt="Ikona šipky">
                    </div>
                    <ul class="custom-options">
                        <?php foreach ($naturalsInGroup as $natural) :?>
                            <li class="custom-option <?php if ($natural->getName() == $report->getNaturalName()) : ?>selected<?php endif ?>">
                            <?= $natural->getName() ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="report-url"><?= $report->getUrl() ?></div>
                <div class="report-url-edit" style="display: none">
                    <textarea type=url size="1" class="text-field"><?= $report->getUrl() ?></textarea>
                </div>
        <span class="report-reason"><?= $report->getReason() ?></span>
        <span class="report-additional-info"><?= $report->getAdditionalInformation() ?></span>
        <span class="report-number"><?= $report->getReportersCount() ?></span>
        <div class="report-action">
              <button class='btn icon show-picture-button' title='Zobrazit obrázek'>
                <img src='images/eye-black.svg' alt="Zobrazit obrázek">
             </button>
             <button class="btn icon edit-picture-button" title='Upravit údaje obrázku'>
                <img src='images/pencil-black.svg' alt="Upravit údaje obrázku">
              </button>
            <button class='btn icon delete-picture-button' title='Odstranit obrázek'>
                <img src='images/trash-black.svg' alt="Odstranit obrázek">
            </button>
            <button class='btn icon delete-report-button' title='Odstranit hlášení'>
                <img src='images/minus-black.svg' alt="Odstranit hlášení">
            </button>
            <div class="report-edit-buttons" style="display: none;">
                <button class='btn icon show-picture-button' title='Zobrazit obrázek'>
                    <img src='images/eye-black.svg' alt="Zobrazit obrázek">
                </button>
                <button class='btn icon edit-picture-confirm-button' title='Uložit'>
                    <img src='images/tick.svg' alt="Uložit">
                </button>
                <button class='btn icon edit-picture-cancel-button'title='Zrušit'>
                    <img src='images/cross-thick-black.svg' alt="Zrušit">
                </button>
            </div>
        </div>
        <div class="report-image" style="display: none">
            <button class="btn icon hide-picture-button" title="Skrýt obrázek"><img src="images/cross-thin-white.svg" alt="Skrýt obrázek"></button>
            <img src="images/blank.gif" alt="Náhled obrázku">
            </div>
        </div>
    <?php endforeach ?>
</div>