<div id="resolve-reports-wrapper">
	<div class="reports-data-properties" <?php if (count($reports) === 0) : ?>style="display: none"<?php endif ?>>
        <span class="report-name">Přírodnina</span>
        <span class="report-url">Zdroj</span>
        <span class="report-reason">Důvod</span>
        <span class="report-additional-info">Další informace</span>
        <span class="report-number">Počet nahlášení</span>
        <span class="report-action">Akce</span>
    </div>
    <?php if (count($reports) === 0) : ?>
    <p>Žádná hlášení k vyřízení</p>
    <?php endif ?>
    <?php foreach ($reports as $report) : ?>
        <div class="reports-data-item" data-picture-id="<?= $report->getPictureId() ?>" data-report-url=<?= $report->getUrl() ?>>
			<span class="report-name"><?= $report->getNaturalName() ?></span>
            <div class="report-name-edit" style="display: none">
				<div class="custom-select-wrapper" id="report-natural-select">
					<div class="custom-select">
						<div class="custom-select-main">
							<span><?= $report->getNaturalName() ?></span>
							<img class="arrow" src="../images/arrowBlack.svg">
						</div>
						<ul class="custom-options">
							<?php foreach ($naturalsInGroup as $natural) :?>
								<li class="custom-option <?php if ($natural->getName() == $report->getNaturalName()) : ?>selected<?php endif ?>">
								<?= $natural->getName() ?></li>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
        	</div>
            <div class="report-url"><?= $report->getUrl() ?></div>
			<div class="report-url-edit" style="display: none">
				<textarea type=url size="1" class="text-field"><?= $report->getUrl() ?></textarea>
			</div>
            <span class="report-reason"><?= $report->getReason() ?></span>
            <span class="report-additional-info"><?= $report->getAdditionalInformation() ?></span>
            <span class="report-number"><?= $report->getReportersCount() ?></span>
            <div class="report-action">
                <button class='btn icon show-picture-button' onclick='showPicture("<?= $report->getUrl() ?>")' title='Zobrazit obrázek'>
                    <img src='images/eye.svg'/>
                </button>
                <button class="btn icon edit-picture-button" title='Upravit údaje obrázku'>
                    <img src='images/pencil.svg'/>
                </button>
                <button class='btn icon' onclick='disablePicture(event, <?= $report->getPictureId() ?>, false)' title='Skrýt obrázek'>
                    <img src='images/dot.svg'/>
                </button>
                <button class='btn icon' onclick='deletePicture(event, <?= $report->getPictureId() ?>, false)' title='Odstranit obrázek'>
                    <img src='images/cross.svg'/>
                </button>
				<div class="report-edit-buttons" style="display: none;">
                    <button class='btn icon edit-picture-confirm-button' title='Uložit'>
                    	<img src='images/tick.svg'/>
                    </button>
                    <button class='btn icon edit-picture-cancel-button'title='Zrušit'>
                    	<img src='images/cross.svg'/>
                    </button>
                </div>
            </div>
			<div class="report-image" style="display: none">
				<img src="">
			</div>
        </div>
    <?php endforeach ?>
</div>