<table id="reports-table">
    <tr>
        <th>Třída / Poznávačka / Část</th>
        <th>Přírodnina</th>
        <th>Zdroj</th>
        <th>Důvod</th>
        <th>Další informace</th>
        <th>Počet nahlášení</th>
        <th>Akce</th>
    </tr>
    <?php if (count($reports) === 0) : ?>
    <tr><td colspan=7>Žádná hlášení k vyřízení</td></tr>
    <?php endif ?>
    <?php foreach ($reports as $report) : ?>
        <tr class='report-data-item'
            data-picture-id="<?= $report->getPictureId() ?>"
            data-report-id="<?= $report->getId() ?>"
            data-report-url="<?= $report->getUrl() ?>">
            <td>
            <?php foreach ($report->getPicturePaths() as $path) : ?>
                <li><?= $path ?></li>
            <?php endforeach ?>
            </td>
            <td><?= $report->getPicture()->getNatural()->getName() ?></td>
            <td><?= $report->getUrl() ?></td>
            <td><?= $report->getReason() ?></td>
            <td><?= $report->getAdditionalInformation() ?>
            <td><?= $report->getReportersCount() ?></td>
            <td class="report-action">
                <div>
                    <button class='btn icon show-picture-button' title='Zobrazit obrázek'>
                        <img src='images/eye.svg'/>
                    </button>
                    <button class='btn icon delete-picture-button' title='Odstranit obrázek'>
                        <img src='images/trash-black.svg'/>
                    </button>
                    <button class='btn icon delete-report-button' title='Odstranit hlášení'>
                        <img src='images/minus.svg'/>
                    </button>
                </div>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<div id="report-image" style="display: none">
    <button class="btn icon hide-picture-button" title="Skrýt obrázek"><img src="../images/crossButtonWhite.svg" alt="Skrýt obrázek"></button>
    <img src="" alt="Náhled obrázku">
    </div>
</div>
