<form method="POST">
    <h3>Žádost o založení nové třídy</h3>
    <?php if (!$specifiedEmail) : ?>
        <span>Kontaktní e-mailová adresa</span>
        <br>
        <input class='text' id='newClassFormEmail' name="email" type=email, length=255 value="<?= @$emailValue ?>" required />
        <br>
    <?php endif ?>
    <span>Požadovaný název třídy</span><img src="images/info.svg" title="Název nesmí kolidovat s jakoukoliv jinou třídou, která se později na stránkách může objevit. Proto vám doporučujeme zahrnout i název školy."/>
    <br>
    <input id='newClassFormName' class="text" name="className" type=text maxlength=31 value="<?= @$classNameValue ?>" required />
    <br>
    <span>Kód třídy</span><img src="images/info.svg" title="Třída bude po vytvoření nastavena jako soukromá. Pro přístup do třídy budou muset uživatelé nejprve zadat čtyřciferný vstupní kód. Tím se jim třída trvale odemkne. Kód si můžete později v nastavení třídy změnit. Můžete ho také odebrat a udělat třídu veřejnou nebo ji naopak uzamknout pro nové uživatele úplně."/>
    <br>
    <input id='newClassFormCode' class="text" name="classCode" type=number min=0 max=9999 maxlength=4 value=<?= @$classCodeValue ?> required />
    <br>
    <span>Je ještě něco, co bychom měli vědět?</span>
    <br>
    <textarea class="text" id='newClassFormInfo' name="text"><?= @$textValue ?></textarea>
    <br>
    <span>Prokažte prosím, že nejste robot opsáním následujícího čísla pomocí číslic: <?= $antispamCode ?></span>
    <br>
    <input id='newClassFormAntispam' class="text" name="antispam" type=number min=0 max=99 maxlength=2 required />
    <br>
    <input type=submit class="button" value="Odeslat žádost" />
    <a href="menu">Zpět</a>
</form>