<div id="sql">
    <div id="sql-warning" class="sql-center">
        Neuvědomělé používání tohoto nástroje může mít destruktivní účinky. Používejte tento nástroj pouze v případě, že jste si naprosto jistí tím, co děláte!
    </div>
    <div id="sql-query" class="sql-center">
        <textarea id="sql-query-input" rows=5 cols=150 placeholder="Zadejte příkazy. Každý příkaz musí být ukončen středníkem (;)"></textarea>
        <br>
        <button class="border-btn" onclick="sendSqlQuery()">Odeslat</button>
    </div>
    <div id="sql-result">
        <span class='sql-center'>Žádný výstup</span>
    </div>
</div>