<div id="sql-warning" class="sql-center">
    Neuvědomělé používání tohoto nástroje může mít destruktivní účinky. Používejte tento nástroj pouze v případě, že jste si naprosto jistí tím, co děláte!
</div>
<div id="sql-query" class="sql-center">
    <textarea id="sql-query-input" placeholder="Zadejte příkazy. Každý příkaz musí být ukončen středníkem (;)"></textarea>
    <button id="send-sql-query-button" class="btn border-btn">Odeslat</button>
</div>
<div id="sql-result">
    <span class='sql-center'>Žádný výstup</span>
</div>
