<div id="tests-wrapper">
    <section class="tests-data-section">
        <div class="test data-properties" <?php if (count($groups) == 0) : ?> style="display:none" <?php endif ?>>
            <span class='test name'>Název</span>
            <span class='test parts'>Části</span>
            <span class='test action'>Akce</span>
        </div>
        <?php foreach ($groups as $group) : ?>
        <div class='test data-item' data-group-id='<?= $group->getId() ?>' data-group-name='<?= $group->getName() ?>'>
            <span class='test name'><?= $group->getName() ?></span>
            <span class='test parts'><?= $group->getPartsCount() ?></span>
            <div class='test action'>
                <a class='btn icon' href='<?= $baseUrl.'/'.$group->getUrl() ?>/reports' title="Spravovat hlášení"><img src="images/list-filled-black.svg"></a>
                <a class='btn icon' href='<?= $baseUrl.'/'.$group->getUrl() ?>/edit' title="Upravit poznávačku"><img src="images/pencil-black.svg"></a>
                <a class='btn icon delete-group-button' title="Odstranit poznávačku"><img src="images/trash-black.svg"></a>
            </div>
        </div>
        <?php endforeach ?>
    </section>
    <section class="tests-new-section">
        <button id='new-test-button' class="btn border-btn non-transparent black">Vytvořit novou poznávačku</button>
        <div id='new-test' class="form" style="display: none;">
            <h3>Nová poznávačka</h3>
            <p>Zadej název nové poznávačky. Do poznávačky budeš moci přidat části a přírodniny později.</p>
            <label for="new-test-name">Název poznávačky</label>
            <input id='new-test-name' type='text' class='text-field' maxlength=31>
            <button id="new-test-confirm-button" class='btn border-btn non-transparent black submit-button'>Vytvořit</button>
            <button id="new-test-cancel-button" class='btn inline black cancel-button'>Zrušit</button>
        </div>
    </section>
</div>

<div id="test-template" class="data-item-template" style="display: none">
    <div class='test data-item'  data-group-id='{id}' data-group-name='{name}'>
        <span class='test name'>{name}</span>
        <span class='test parts'>{parts}</span>
        <div class='test action'>
            <a class='btn icon' href='<?= $baseUrl.'/' ?>{url}/reports' title="Spravovat hlášení"><img src="images/list-filled-black.svg"></a>
            <a class='btn icon' href='<?= $baseUrl.'/' ?>{url}/edit' title="Upravit poznávačku"><img src="images/pencil-black.svg"></a>
            <a class='btn icon delete-group-button' title="Odstranit poznávačku"><img src="images/trash-black.svg"></a>
        </div>
    </div>
</div>