<h2>Vyzkoušet se</h2>
<section>
	<img <?= ?>> <!-- VYGENEROVÁNÍ OBRÁZKU -->
	<button onclick="reportImg(event)"></button>
	<div>
		<?= ?> <!-- ZOBRAZENÍ REPORT FORM -->
	</div>
</section>
<section>
	<form onsubmit="answer(event)">
		<input type=text autocomplete="off" placeholder="Zadejte odpověď">
		<input type=submit value="OK" />
    </form>
	<div>
		<?= ?> <!-- ZHODNOCENÍ ODPOVĚDI -->
	</div>
</section>