<section id="settings-wrapper" class="study-wrapper">
    <p>Aplikace ti vygeneruje test a spočítá ti statistiky úspěšnosti. Na konci testu si ještě budeš moci projít špatně zodpovězené přírodniny. </p>
    <form id="test-settings">
        <p>Zvol si, kolik otázek bude test obsahovat:</p>
        <div class="buttons-wrapper">
            <button class="btn border-btn transparent primary test-pics-num-button selected">10 otázek</button>
            <button class="btn border-btn transparent primary test-pics-num-button">20 otázek</button>
            <button class="btn border-btn transparent primary test-pics-num-button">30 otázek</button>
        </div>
        <label for="test-pics-num">Jiný počet otázek:</label>
        <input type=text autocomplete="off" id="test-pics-num" class="text-field" />
        <p>Zvol si časový limit testu:</p>
        <div class="buttons-wrapper">
            <button class="btn border-btn transparent primary test-pics-num-button selected">Žádný limit</button>
            <button class="btn border-btn transparent primary test-pics-num-button">5 minut</button>
            <button class="btn border-btn transparent primary test-pics-num-button">10 minut</button>
        </div>
        <label for="test-pics-num">Jiný čas:</label>
        <input type=text autocomplete="off" id="test-pics-time" class="text-field" />
    </form>
</section>

<section id="test-wrapper" class="study-wrapper" data-preact="test-section">    
</section>

<section id="results-wrapper" class="study-wrapper">
    <p>Zodpověděl*a jsi správně 15/20 otázek.</p>
    <button class="btn border-btn non-transparent primary new-test-button">Otestovat, co mi nešlo</button>
    <!-- ukáže se popup, jestli zobrazovat stejné obrázky, nebo náhodné  -->
    <button class="btn border-btn non-transparent primary new-test-button">Zobrazit správné odpovědi</button>
    <button class="btn border-btn non-transparent primary new-test-button">Nový test</button>
</section>

<section id="answers-wrapper" class="study-wrapper">

    <div id="cards"
        data-preact="answer-cards"
    ></div>

    <button class="btn border-btn non-transparent primary new-test-button">Nový test</button>
</section>