<h2>Vyzkoušet se</h2>
<section>
	<img id="main-img" src="images/imagePreview.png" /> <!-- Adresa bude dodána JavaScriptem -->
	<div>
		<?php require 'Views/reportForm.phtml'; ?>
	</div>
</section>
<section>
	<form onsubmit="answer(event)" id="answerForm">
		<input type=text autocomplete="off" placeholder="Zadejte odpověď" id="textfield" />
		<input type=hidden id="hiddenInput" />
		<input type=submit value="OK" />
    </form>
	<div id="result">
		<!-- ZHODNOCENÍ ODPOVĚDI -->
		<span id="resultText"></span>
		<button onclick="next()" id="nextButton">Další obrázek</button>
	</div>
</section>