<table>
    <tr>
        <th>ID</th>
        <th>Jméno</th>
        <th>E-mail</th>
        <th>Poslední přihlášení</th>
        <th>Přidané obrázky</th>
        <th>Uhodnuté obrázky</th>
        <th>Karma</th>
        <th>Status</th>
        <th>Akce</th>
    </tr>
    <?php foreach($users as $user) : ?>
        <tr class="user data-item"
            data-user-id="<?= $user['id'] ?>"
            data-user-mail="<?= $user['email'] ?>"
            data-user-name="<?= $user['name'] ?>">
            <td>
                <?= $user['id'] ?>
            </td>
            <td>
                <?= $user['name'] ?>
            </td>
            <td>
                <?= $user['email'] ?>
            </td>
            <td>
                <?= $user['lastLogin']->format('Y-m-d H:i:s') ?>
            </td>
            <td>
                <input type=number readonly value="<?= $user['addedPictures'] ?>" class='user field'/>
            </td>
            <td>
                <input type=number readonly value="<?= $user['guessedPictures'] ?>" class='user field'/>
            </td>
            <td>
                <input type=number readonly value="<?= $user['karma'] ?>" class='user field'/>
            </td>
            <td>
                <select disabled class='user field'>
                    <?php if ($user['status'] === Poznavacky\Models\DatabaseItems\User::STATUS_ADMIN) : ?>
                    <option selected><?= Poznavacky\Models\DatabaseItems\User::STATUS_ADMIN ?></option>
                    <?php endif ?>
                    <?php if ($user['status'] !== Poznavacky\Models\DatabaseItems\User::STATUS_ADMIN) : ?>
                    <option><?= Poznavacky\Models\DatabaseItems\User::STATUS_ADMIN ?></option>
                    <?php endif ?>
                    
                    <?php if ($user['status'] === Poznavacky\Models\DatabaseItems\User::STATUS_CLASS_OWNER) : ?>
                    <option selected><?= Poznavacky\Models\DatabaseItems\User::STATUS_CLASS_OWNER ?></option>
                    <?php endif ?>
                    <?php if ($user['status'] !== Poznavacky\Models\DatabaseItems\User::STATUS_CLASS_OWNER) : ?>
                    <option><?= Poznavacky\Models\DatabaseItems\User::STATUS_CLASS_OWNER ?></option>
                    <?php endif ?>
                    
                    <?php if ($user['status'] === Poznavacky\Models\DatabaseItems\User::STATUS_MEMBER) : ?>
                    <option selected><?= Poznavacky\Models\DatabaseItems\User::STATUS_MEMBER ?></option>
                    <?php endif ?>
                    <?php if ($user['status'] !== Poznavacky\Models\DatabaseItems\User::STATUS_MEMBER) : ?>
                    <option><?= Poznavacky\Models\DatabaseItems\User::STATUS_MEMBER ?></option>
                    <?php endif ?>
                    
                    <?php if ($user['status'] === Poznavacky\Models\DatabaseItems\User::STATUS_GUEST) : ?>
                    <option selected><?= Poznavacky\Models\DatabaseItems\User::STATUS_GUEST ?></option>
                    <?php endif ?>
                    <?php if ($user['status'] !== Poznavacky\Models\DatabaseItems\User::STATUS_GUEST) : ?>
                    <option><?= Poznavacky\Models\DatabaseItems\User::STATUS_GUEST ?></option>
                    <?php endif ?>
                </select>
            </td>
            <td class="user action">
                <div>
                    <button class='btn icon edit-button' title='Upravit'>
                        <img src='images/pencil-colour.svg'/>
                    </button>
                    <div class="edit-buttons" style="display: none">
                        <button class='btn icon edit-confirm-button' title='Uložit'>
                            <img src='images/tick.svg'/>
                        </button>
                        <button class='btn icon edit-cancel-button' title='Zrušit'>
                            <img src='images/cross-thick-black.svg'/>
                        </button>
                    </div>
                    <?php if (empty($user['email'])) : ?>
                    <button class='btn icon disabled'>
                    <?php endif ?>
                    <?php if (!empty($user['email'])) : ?>
                    <button class='btn icon start-mail-button' title='Poslat e-mail'>
                    <?php endif ?>
                        <img src='images/mail-colour.svg'/>
                    </button>
                    <button class='btn icon delete-user-button' title='Odstranit'>
                        <img src='images/trash-black.svg'/>
                    </button>
                </div>
            </td>
        </tr>
    <?php endforeach ?>
</table>