<table width='100%' cellpadding='0' border='0' cellspacing='0'>
    <tbody>
        <tr>
            <td align='center' bgcolor='#eeeeee'>
                <table width='660' cellpadding='0' border='0' cellspacing='0' align='center' bgcolor='#FFFFFF' style='font-size:15px;font-family:Helvetica,Arial,sans-serif;line-height:25px;color:#445566;border-top: 10px solid #405d27;'>
                    <tbody>
                        <tr>
                            <td align='left' style='padding:45px 50px 45px 50px'>
                                <div>
                                    <p>
                                        Na základě vaší žádosti na <a href='<?= $websiteAddress ?>'><?= $websiteAddress ?></a> bylo změněno jméno vámi spravované třídy <b><?= $oldName ?></b> na <b><?= $newName ?></b>.
                                        <br>
                                        Doporučujeme vám informovat členy vaší třídy o této změně, aby se předešlo jejich zmatení.
                                    </p>
                                    <p>
                                    	Pokud si přejete změnit jméno zpět na staré nebo nějaké úplně jiné, můžete tak učinit odesláním další žádosti o změnu jména ve správě vaší třídy.
                                	</p>
                                    <p>
                                    	Neodesílali jste žádnou žádost na změnu jména této třídy? Je možné, že ji odeslal předchozí správce této třídy. Pokud to tak není, někdo pravděpodobně získal přístup k vašemu účtu. Doporučujeme vám si co nejdříve změnit vaše heslo. Pokud se nemůžete přihlásit, kontaktujte nás prosím na e-mailové adrese <a href='mailto:poznavacky@email.com'>poznavacky@email.com</a>.
                                    </p>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <table width='660' cellpadding='0' border='0' cellspacing='0' align='center' style='font-family:Arial,Helvetica,sans-serif;color:#666666;font-size:12px;line-height:18px;text-align:center;'>
                    <tbody>
                        <tr>
                            <td>
                                <div>
                                    <p style='margin-top:30px;margin-bottom:30px'>
    									<p>Toto je automaticky vygenerovaná zpráva. Prosíme, neodpovídejte na ni.</p>";
                                    </p>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>