<!doctype html>
<html>
  <body class="" style="background-color: #f6f6f6;font-family: consolas;font-size: 14px;margin: 0;padding: 0;">
    <div class="content" style="box-sizing: border-box;margin: 0 auto;max-width: 580px;padding: 10px;">
      <h1 style="margin: 0;margin-bottom: 30px;font-family: Ubuntu, sans-serif;font-size: 32px;font-weight: 300;">
        <?= $title ?>
      </h1>
      <div role="presentation" class="main" style="background: #000000;border-radius: 3px;border-top: 12px solid #<?= $barColor ?>;padding: 5px;color: white;" width="100%">
        <?= $content ?>
      </div>
    </div>
</body></html>