<table width='100%' cellpadding='0' border='0' cellspacing='0'>
    <tbody>
        <tr>
            <td align='center' bgcolor='#eeeeee'>
                <table width='660' cellpadding='0' border='0' cellspacing='0' align='center' bgcolor='#FFFFFF' style='font-size:15px;font-family:Helvetica,Arial,sans-serif;line-height:25px;color:#445566;border-top: 10px solid #405d27;'>
                    <tbody>
                        <tr>
                            <td align='left' style='padding:45px 50px 45px 50px'>
                                <div>
                                    <p>Pro obnovení vašeho hesla klikněte na tento odkaz: <a href='<?= $recoveryLink ?>'>OBNOVIT HESLO</a></p>
                                    <p>Tento odkaz bude platný po následujících 24 hodin, nebo do odeslání žádosti o nový kód.</p>
                                    <p style='color: #990000;'><span style='font-weight: bold;'>DŮLEŽITÉ: </span><span>Tento e-mail nikomu nepřeposílejte! Mohl by získat přístup k vašemu účtu.</span>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <table width='660' cellpadding='0' border='0' cellspacing='0' align='center' style='font-family:Arial,Helvetica,sans-serif;color:#666666;font-size:12px;line-height:18px;text-align:center;'>
                    <tbody>
                        <tr>
                            <td>
                                <div>
                                    <p style='margin-top:30px;margin-bottom:30px'>
    									<p>Pokud jste o obnovu hesla nezažádali, můžete tento e-mail ignorovat.</p>
    									<p>V případě problémů nás kontaktujte na <a href='mailto:poznavacky@email.com'>poznavacky@email.com</a></p>
										<p>Toto je automaticky vygenerovaná zpráva. Prosíme, neodpovídejte na ni.</p>
                                    </p>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>