<table width='100%' cellpadding='0' border='0' cellspacing='0'>
    <tbody>
        <tr>
            <td align='center' bgcolor='#eeeeee'>
                <table width='660' cellpadding='0' border='0' cellspacing='0' align='center' bgcolor='#FFFFFF' style='font-size:15px;font-family:Helvetica,Arial,sans-serif;line-height:25px;color:#445566;border-top: 10px solid #405d27;'>
                    <tbody>
                        <tr>
                            <td align='left' style='padding:45px 50px 45px 50px'>
                                <div>
                                    <p>
                                    	Vaše žádost o změnu uživatelského jména na <a href='<?= $websiteAddress ?>'><?= $websiteAddress ?></a> byla administrátorem zamítnuta.
                                    	<br>
                                    	<b>Důvod zamítnutí: <span style='color:#990000'><?= $declineReason ?></span></b>
                                    	<br>
                                    	Vaše současné jméno (<b><?= $oldName ?></b>) tak stále zůstává platným přihlašovacím údajem.
                                	</p>
                                    <p>
                                    	Pokud si jméno stále chcete změnit, můžete odeslat novou žádost o změnu. Neodesílejte však prosím žádost o změnu na jméno, které bylo zamítnuto.
                                	</p>
                                    <p>
                                    	Neodesílali jste žádnou žádost na změnu uživatelského jména? Je možné, že někdo získal přístup k vašemu účtu. Doporučujeme vám si co nejdříve změnit vaše heslo. Pokud se nemůžete přihlásit, kontaktujte nás prosím na e-mailové adrese <a href='mailto:poznavacky@email.com'>poznavacky@email.com</a>.
                                	</p>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <table width='660' cellpadding='0' border='0' cellspacing='0' align='center' style='font-family:Arial,Helvetica,sans-serif;color:#666666;font-size:12px;line-height:18px;text-align:center;'>
                    <tbody>
                        <tr>
                            <td>
                                <div>
                                    <p style='margin-top:30px;margin-bottom:30px'>
    									<p>Toto je automaticky vygenerovaná zpráva. Prosíme, neodpovídejte na ni.</p>";
                                    </p>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>